import type { AppMessage } from '../types/message';

// Reference date: May 9, 2026
export const messageData: AppMessage[] = [
  // === SU only: Contract alerts (aggregated) ===
  {
    id: 'msg-001',
    category: 'contract-expired',
    title: '2 台设备已出保',
    body: 'MR 5300 和 Lumify 便携超声的服务合同已到期，设备当前无服务保障，建议尽快联系续约。',
    time: '2026-05-01',
    isRead: false,
    forAdminOnly: true,
    isAggregated: true,
    devices: [
      { id: 'dev-004', name: 'MR 5300', department: '放射科', summary: '合同于 2025-12-31 到期' },
      { id: 'dev-007', name: 'Lumify 便携超声', department: '急诊科', summary: '暂无服务合同' },
    ],
  },
  {
    id: 'msg-002',
    category: 'contract-expiry',
    title: '3 台设备合同即将出保',
    body: 'Affiniti 70、Azurion M3、BigBore CT 7500 的服务合同将在 4 个月内到期，请提前安排续约。',
    time: '2026-04-28',
    isRead: false,
    forAdminOnly: true,
    isAggregated: true,
    devices: [
      { id: 'dev-006', name: 'Affiniti 70', department: '心内科', summary: '合同于 2026-06-20 到期，还剩 42 天' },
      { id: 'dev-002', name: 'Azurion M3', department: '导管室', summary: '合同于 2026-07-15 到期，还剩 67 天' },
      { id: 'dev-005', name: 'BigBore CT 7500', department: '放射治疗科', summary: '合同于 2026-09-30 到期，还剩 144 天' },
    ],
  },
  // === SU only: Acceptance reminder (aggregated) ===
  {
    id: 'msg-003',
    category: 'acceptance',
    title: '2 台设备待验收',
    body: '以下设备已完成装机但尚未验收，验收前设备处于无保状态。每 3 个月提醒一次，请及时跟进。',
    time: '2026-05-01',
    isRead: false,
    forAdminOnly: true,
    isAggregated: true,
    devices: [
      { id: 'dev-010', name: 'EPIQ Elite', department: '妇产科', summary: '装机于 2026-02-15，待验收已 83 天' },
      { id: 'dev-011', name: 'Ingenia Ambition 1.5T', department: '神经内科', summary: '装机于 2026-01-20，待验收已 109 天' },
    ],
  },
  // === SU only: PM plan (aggregated) ===
  {
    id: 'msg-004',
    category: 'pm-plan',
    title: '5 月 PM 计划 · 5 台设备',
    body: '本月共 5 台设备有预防性维护计划，请知悉并安排停机时间。',
    time: '2026-05-01',
    isRead: false,
    forAdminOnly: true,
    isAggregated: true,
    devices: [
      { id: 'dev-001', name: 'Azurion M3', department: '导管室', summary: '计划日期：5 月 1 日' },
      { id: 'dev-003', name: 'BigBore CT 7500', department: '放射治疗科', summary: '计划日期：5 月 1 日' },
      { id: 'dev-005', name: 'Vereos PET/CT', department: '核医学科', summary: '计划日期：5 月 1 日' },
      { id: 'dev-008', name: 'Ingenia 3.0T', department: '放射科', summary: '计划日期：5 月 15 日' },
      { id: 'dev-009', name: 'Affiniti 70', department: '心内科', summary: '计划日期：5 月 15 日' },
    ],
  },
  // === Both: PM risk (aggregated) ===
  {
    id: 'msg-005',
    category: 'pm-risk',
    title: '2 台设备存在 PM 风险',
    body: '以下设备已出保且长期未进行预防性维护，建议尽快安排保养或续签服务合同。',
    time: '2026-05-01',
    isRead: false,
    forAdminOnly: false,
    isAggregated: true,
    devices: [
      { id: 'dev-004', name: 'MR 5300', department: '放射科', summary: '上次保养：2025-06-10，已超 11 个月' },
      { id: 'dev-007', name: 'Lumify 便携超声', department: '急诊科', summary: '无服务合同，长期未保养' },
    ],
  },
  // === Both: Work order — pending signature only ===
  {
    id: 'msg-006',
    category: 'order-update',
    title: '工单待签字 · Ingenia 3.0T',
    body: 'Ingenia 3.0T 保养工单已完成，请前往工单列表完成签字确认。',
    time: '2026-05-08',
    isRead: false,
    forAdminOnly: false,
    deviceId: 'dev-008',
    deviceName: 'Ingenia 3.0T',
    workOrderId: 'pm001-2',
  },
  // === U only: Permission upgrade ===
  {
    id: 'msg-008',
    category: 'permission-upgrade',
    title: '权限升级申请已通过',
    body: '您的 Super User 权限申请已由管理员审核通过，现可查看全院设备列表、合同信息及 PM 风险提醒。',
    time: '2026-04-15',
    isRead: true,
    forAdminOnly: false,
  },
  // === Temporary extra messages for SU pagination preview ===
  {
    id: 'msg-009',
    category: 'contract-expiry',
    title: '2 台设备合同将在 90 天内到期',
    body: 'Brilliance CT 与 EPIQ Elite 合同将于 90 天内到期，请提前确认续约预算。',
    time: '2026-05-07',
    isRead: false,
    forAdminOnly: true,
    isAggregated: true,
    devices: [
      { id: 'dev-003', name: 'Brilliance CT', department: '影像科', summary: '合同剩余 76 天' },
      { id: 'dev-010', name: 'EPIQ Elite', department: '心内科', summary: '合同剩余 84 天' },
    ],
  },
  {
    id: 'msg-010',
    category: 'acceptance',
    title: '1 台设备待验收 · Affiniti 70',
    body: 'Affiniti 70 已完成安装，请尽快安排验收，避免保障期风险。',
    time: '2026-05-06',
    isRead: false,
    forAdminOnly: true,
    deviceId: 'dev-006',
    deviceName: 'Affiniti 70',
  },
  {
    id: 'msg-011',
    category: 'pm-plan',
    title: '本周 PM 计划新增 2 台设备',
    body: '本周新增 PM 计划设备 2 台，请确认停机窗口并与临床科室对齐。',
    time: '2026-05-06',
    isRead: false,
    forAdminOnly: true,
    isAggregated: true,
    devices: [
      { id: 'dev-002', name: 'Azurion M3', department: '导管室', summary: '计划日期：5 月 13 日' },
      { id: 'dev-009', name: 'IDS 7 放射信息系统', department: '影像科', summary: '计划日期：5 月 14 日' },
    ],
  },
  {
    id: 'msg-012',
    category: 'order-update',
    title: '工单待签字 · MR 5300',
    body: 'MR 5300 故障处理已完成，请前往工单列表进行签字确认。',
    time: '2026-05-05',
    isRead: false,
    forAdminOnly: false,
    deviceId: 'dev-004',
    deviceName: 'MR 5300',
    workOrderId: 'wo-r5300-001',
  },
  {
    id: 'msg-013',
    category: 'pm-risk',
    title: '1 台设备 PM 逾期风险',
    body: 'BigBore CT 7500 已超过建议保养周期，请尽快安排 PM。',
    time: '2026-05-04',
    isRead: true,
    forAdminOnly: false,
    deviceId: 'dev-005',
    deviceName: 'BigBore CT 7500',
  },
  {
    id: 'msg-014',
    category: 'contract-expired',
    title: '1 台设备服务合同已到期',
    body: 'Lumify 便携超声服务合同已到期，请评估是否续签或纳入院内维护。',
    time: '2026-05-03',
    isRead: false,
    forAdminOnly: true,
    deviceId: 'dev-007',
    deviceName: 'Lumify 便携超声',
  },
  {
    id: 'msg-015',
    category: 'permission-upgrade',
    title: '新成员权限申请待确认',
    body: '设备科成员提交了权限申请，请在权限管理中审核处理。',
    time: '2026-05-02',
    isRead: false,
    forAdminOnly: true,
  },
  {
    id: 'msg-016',
    category: 'order-update',
    title: '工单状态更新 · Vereos PET/CT',
    body: 'Vereos PET/CT 保养工单已派工，预计明日上午到场。',
    time: '2026-05-01',
    isRead: true,
    forAdminOnly: false,
    deviceId: 'dev-008',
    deviceName: 'Vereos PET/CT',
    workOrderId: 'wo-petct-008',
  },
];
