import { style } from '@vanilla-extract/css';

export const shellStyles = {
  shell: style({
    width: '100%',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    position: 'relative',
  }),
  content: style({
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    scrollbarWidth: 'none',
    '::-webkit-scrollbar': {
      display: 'none',
    },
  }),
  bottomBar: style({
    flexShrink: 0,
  }),
  scanFab: style({
    position: 'absolute',
    bottom: 64,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 44,
    height: 44,
    borderRadius: '50%',
    backgroundColor: '#0161de',
    border: '3px solid #fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    zIndex: 20,
    boxShadow: '0 2px 10px rgba(1,97,222,0.35)',
  }),
  scanOverlay: style({
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.45)',
    zIndex: 50,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
  }),
  scanSheet: style({
    backgroundColor: '#fff',
    borderRadius: '16px 16px 0 0',
    padding: '20px 16px 32px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  }),
  scanSheetTitle: style({
    fontSize: 15,
    fontWeight: 600,
    color: '#111',
    textAlign: 'center',
    marginBottom: 6,
  }),
  scanOptionBtn: style({
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: '14px 16px',
    borderRadius: 12,
    backgroundColor: '#f5f7fa',
    border: 'none',
    cursor: 'pointer',
    width: '100%',
    textAlign: 'left',
  }),
  scanOptionIconWrap: style({
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#0161de',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  }),
  scanOptionLabel: style({
    fontSize: 15,
    fontWeight: 500,
    color: '#111',
  }),
  scanOptionSub: style({
    fontSize: 12,
    color: '#888',
    marginTop: 1,
  }),
  scanCancelBtn: style({
    marginTop: 4,
    padding: '13px',
    borderRadius: 12,
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: 15,
    color: '#888',
    width: '100%',
  }),
};
