import { style } from '@vanilla-extract/css';

export const detailStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    backgroundColor: '#f5f7fa',
  }),
  header: style({
    backgroundColor: '#0161de',
    padding: '14px 16px 16px',
    flexShrink: 0,
  }),
  headerTop: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 6,
  }),
  backBtn: style({
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px 0',
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
  }),
  headerName: style({
    color: '#ffffff',
    fontSize: 17,
    fontWeight: 700,
    lineHeight: '24px',
    flex: 1,
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  headerMeta: style({
    paddingLeft: 34,
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    lineHeight: '18px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  headerChips: style({
    paddingLeft: 34,
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  }),
  chip: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '2px 8px',
    borderRadius: 4,
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '18px',
  }),
  chipSuccess: style({
    background: 'rgba(22,163,74,0.18)',
    color: '#bbf7d0',
    border: '1px solid rgba(22,163,74,0.35)',
  }),
  chipWarning: style({
    background: 'rgba(234,179,8,0.18)',
    color: '#fef08a',
    border: '1px solid rgba(234,179,8,0.35)',
  }),
  chipError: style({
    background: 'rgba(239,68,68,0.18)',
    color: '#fca5a5',
    border: '1px solid rgba(239,68,68,0.35)',
  }),
  chipNeutral: style({
    background: 'rgba(255,255,255,0.15)',
    color: 'rgba(255,255,255,0.85)',
    border: '1px solid rgba(255,255,255,0.25)',
  }),
  chipActive: style({
    background: 'rgba(96,165,250,0.25)',
    color: '#bfdbfe',
    border: '1px solid rgba(96,165,250,0.4)',
  }),
  scrollContent: style({
    flex: 1,
    overflowY: 'auto',
    scrollbarWidth: 'none',
    '::-webkit-scrollbar': { display: 'none' },
    padding: '12px 0 24px',
  }),
  // Alert banners (before sections)
  alertBannerWarn: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    margin: '0 16px 10px',
    backgroundColor: '#fff8e6',
    border: '1px solid #f0c843',
    borderRadius: 10,
    padding: '10px 14px',
  }),
  alertBannerDanger: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    margin: '0 16px 10px',
    backgroundColor: '#fff1f0',
    border: '1px solid #ffb3b3',
    borderRadius: 10,
    padding: '10px 14px',
  }),
  alertBannerInfo: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    margin: '0 16px 10px',
    backgroundColor: '#f0f6ff',
    border: '1px solid #b3d1ff',
    borderRadius: 10,
    padding: '10px 14px',
  }),
  alertText: style({
    fontSize: 13,
    lineHeight: '18px',
    flex: 1,
    color: '#444',
  }),
  // Section cards
  section: style({
    margin: '0 16px 10px',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
  }),
  sectionHead: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px 8px',
    borderBottom: '1px solid #f2f2f2',
  }),
  sectionTitle: style({
    fontSize: 12,
    fontWeight: 600,
    color: '#888',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  }),
  daysChip: style({
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 3,
    paddingBottom: 3,
    fontSize: 12,
    fontWeight: 600,
  }),
  chipGood: style({ backgroundColor: '#e8f7ef', color: '#0a7c3e' }),
  chipWarn: style({ backgroundColor: '#fff4e0', color: '#7a4800' }),
  chipDanger: style({ backgroundColor: '#ffefef', color: '#c0392b' }),
  // Info rows
  infoRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '11px 16px',
    gap: 8,
    borderBottom: '1px solid #f5f5f5',
  }),
  infoRowLast: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '11px 16px',
    gap: 8,
  }),
  infoLabel: style({
    fontSize: 13,
    color: '#999',
    width: 60,
    flexShrink: 0,
    lineHeight: '20px',
  }),
  infoValue: style({
    fontSize: 14,
    color: '#222',
    lineHeight: '20px',
    flex: 1,
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  infoValueAccent: style({
    fontSize: 14,
    color: '#00126e',
    fontWeight: 700,
    lineHeight: '20px',
    flex: 1,
  }),
  // Service status row
  serviceRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
    padding: '12px 16px',
  }),
  serviceDot: style({
    width: 10,
    height: 10,
    borderRadius: '50%',
    backgroundColor: '#0072db',
    flexShrink: 0,
    marginTop: 5,
  }),
  serviceInfo: style({
    flex: 1,
    minWidth: 0,
  }),
  serviceLabel: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#222',
    lineHeight: '20px',
  }),
  serviceDate: style({
    fontSize: 13,
    color: '#888',
    lineHeight: '18px',
    marginTop: 2,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  serviceEngineer: style({
    fontSize: 13,
    color: '#0072db',
    lineHeight: '18px',
    marginTop: 2,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  // History items
  historyItem: style({
    display: 'flex',
    flexDirection: 'row',
    padding: '10px 16px',
    gap: 12,
    alignItems: 'flex-start',
    borderBottom: '1px solid #f5f5f5',
  }),
  historyItemLast: style({
    display: 'flex',
    flexDirection: 'row',
    padding: '10px 16px',
    gap: 12,
    alignItems: 'flex-start',
  }),
  historyDot: style({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: '#bbb',
    flexShrink: 0,
    marginTop: 6,
  }),
  historyLabel: style({
    fontSize: 14,
    color: '#444',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    flex: 1,
  }),
  historyMeta: style({
    fontSize: 12,
    color: '#999',
    lineHeight: '18px',
    marginTop: 2,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  // Tab bar — scrollable for 5 tabs
  tabBar: style({
    display: 'flex',
    flexDirection: 'row',
    background: '#0161de',
    flexShrink: 0,
    overflowX: 'auto',
    scrollbarWidth: 'none',
    '::-webkit-scrollbar': { display: 'none' },
  }),
  tabBtn: style({
    flex: 1,
    minWidth: 68,
    background: 'none',
    border: 'none',
    padding: '10px 4px',
    fontSize: 13,
    color: 'rgba(255,255,255,0.65)',
    cursor: 'pointer',
    position: 'relative',
    fontWeight: 500,
    letterSpacing: '0.01em',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  }),
  tabBtnActive: style({
    color: '#fff',
    fontWeight: 700,
    ':after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      bottom: 0,
      left: '50%',
      transform: 'translateX(-50%)',
      width: 32,
      height: 3,
      borderRadius: '3px 3px 0 0',
      background: '#fff',
    },
  }),
  // Tab content area
  tabContent: style({
    flex: 1,
    overflowY: 'auto',
    scrollbarWidth: 'none',
    '::-webkit-scrollbar': { display: 'none' },
    padding: '12px 0 24px',
  }),
  // Repair history note banner
  noteBanner: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    margin: '0 16px 10px',
    backgroundColor: '#fffbeb',
    border: '1px solid #fee685',
    borderRadius: 10,
    padding: '10px 14px',
  }),
  noteBannerText: style({
    fontSize: 13,
    color: '#bb4d00',
    lineHeight: '20px',
    flex: 1,
  }),
  // Repair history card items
  repairHistoryCard: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    margin: '0 16px 8px',
    background: '#fff',
    borderRadius: 12,
    padding: '14px 12px 14px 16px',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
    cursor: 'pointer',
    border: '1px solid #f0f0f0',
  }),
  repairHistoryLeft: style({
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  }),
  repairHistoryTopRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  }),
  repairHistoryId: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#0a0a0a',
  }),
  repairHistoryStatusTag: style({
    fontSize: 11,
    padding: '2px 7px',
    borderRadius: 4,
    fontWeight: 600,
    flexShrink: 0,
  }),
  repairHistoryStatusInService: style({
    background: '#e8f0fe',
    color: '#0072db',
  }),
  repairHistoryStatusCompleted: style({
    background: '#f0fdf4',
    color: '#16a34a',
  }),
  repairHistoryStatusCancelled: style({
    background: '#f5f5f5',
    color: '#9ca3af',
  }),
  repairHistoryMeta: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  }),
  repairHistoryMetaRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    fontSize: 12,
    color: '#9ca3af',
  }),
  repairHistoryMetaLabel: style({
    flexShrink: 0,
    width: 56,
  }),
  repairHistoryDesc: style({
    fontSize: 13,
    color: '#374151',
    lineHeight: '18px',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  repairHistoryChevron: style({
    color: '#d1d5db',
    fontSize: 20,
    flexShrink: 0,
  }),
  emptyHistory: style({
    textAlign: 'center',
    padding: '48px 24px',
    color: '#9ca3af',
    fontSize: 14,
  }),
  sectionCount: style({
    fontSize: 12,
    color: '#aaa',
    fontWeight: 400,
  }),
  // Contract timeline
  contractEmpty: style({
    padding: '20px 16px',
    fontSize: 13,
    color: '#aaa',
    textAlign: 'center',
  }),
  contractDotUnsupported: style({
    width: 12,
    height: 12,
    borderRadius: '50%',
    backgroundColor: '#e5e7eb',
    flexShrink: 0,
    marginTop: 4,
  }),
  contractChipUnsupported: style({
    backgroundColor: '#f5f5f5',
    color: '#9ca3af',
  }),
  contractSubType: style({
    fontWeight: 600,
    color: '#1a2234',
  }),
  contractPeriodRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 12,
    padding: '14px 16px',
  }),
  contractPeriodRowBorder: style({
    borderBottom: '1px solid #f5f5f5',
  }),
  contractPeriodRowActive: style({
    backgroundColor: '#f6faff',
  }),
  contractCurrentBody: style({
    padding: '12px 16px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  }),
  contractCurrentType: style({
    fontSize: 16,
    fontWeight: 700,
    color: '#1a2234',
  }),
  contractCurrentSubType: style({
    fontSize: 14,
    fontWeight: 500,
    color: '#6b7280',
  }),
  contractCurrentMeta: style({
    fontSize: 13,
    color: '#8898aa',
  }),
  contractCurrentExpiredText: style({
    fontSize: 13,
    color: '#dc2626',
  }),
  acceptanceCard: style({
    margin: '16px 16px 10px',
    backgroundColor: '#fffbeb',
    border: '1px solid #fcd34d',
    borderRadius: 12,
    padding: '16px',
    display: 'flex',
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  }),
  acceptanceCardBody: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    flex: 1,
  }),
  acceptanceCardTitle: style({
    fontSize: 15,
    fontWeight: 700,
    color: '#92400e',
  }),
  acceptanceCardMeta: style({
    fontSize: 13,
    color: '#b45309',
  }),
  acceptanceCardDesc: style({
    fontSize: 13,
    color: '#6b7280',
    marginTop: 2,
  }),
  contractHistoryNote: style({
    padding: '10px 16px',
    fontSize: 12,
    color: '#9ca3af',
    borderBottom: '1px solid #f5f5f5',
    lineHeight: '18px',
  }),
  contractStatusCard: style({
    margin: '0 16px 10px',
    borderRadius: 12,
    padding: '14px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  }),
  contractStatusGood: style({
    backgroundColor: '#f0fdf4',
    border: '1px solid #86efac',
  }),
  contractStatusWarn: style({
    backgroundColor: '#fffbeb',
    border: '1px solid #fcd34d',
  }),
  contractStatusDanger: style({
    backgroundColor: '#fff1f2',
    border: '1px solid #fca5a5',
  }),
  contractStatusNone: style({
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
  }),
  contractStatusBadge: style({
    display: 'inline-flex',
    alignSelf: 'flex-start',
    padding: '2px 8px',
    borderRadius: 20,
    fontSize: 11,
    fontWeight: 600,
    marginBottom: 2,
  }),
  contractStatusBadgeGood: style({ backgroundColor: '#dcfce7', color: '#15803d' }),
  contractStatusBadgeWarn: style({ backgroundColor: '#fef3c7', color: '#d97706' }),
  contractStatusBadgeDanger: style({ backgroundColor: '#fee2e2', color: '#dc2626' }),
  contractStatusBadgeNeutral: style({ backgroundColor: '#f3f4f6', color: '#6b7280' }),
  contractStatusTitle: style({ fontSize: 15, fontWeight: 700, color: '#1a2234' }),
  contractStatusDetail: style({ fontSize: 13, color: '#374151', lineHeight: '20px' }),
  contractStatusCta: style({ fontSize: 12, color: '#6b7280' }),
  contractStatusDistNote: style({
    fontSize: 11,
    color: '#9ca3af',
    paddingTop: 8,
    marginTop: 2,
    borderTop: '1px solid rgba(0,0,0,0.08)',
  }),
  contractTimeline: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: 16,
    flexShrink: 0,
  }),
  contractDot: style({
    width: 12,
    height: 12,
    borderRadius: '50%',
    backgroundColor: '#d1d5db',
    flexShrink: 0,
    marginTop: 4,
  }),
  contractDotActive: style({ backgroundColor: '#0161de' }),
  contractDotExpired: style({ backgroundColor: '#9ca3af' }),
  contractDotUpcoming: style({ backgroundColor: '#93c5fd' }),
  contractLine: style({
    flex: 1,
    width: 2,
    backgroundColor: '#e5e7eb',
    marginTop: 4,
    marginBottom: -4,
    minHeight: 20,
  }),
  contractPeriodInfo: style({
    flex: 1,
    minWidth: 0,
    paddingBottom: 4,
  }),
  contractPeriodHeader: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  }),
  contractTypeLabel: style({
    fontSize: 14,
    fontWeight: 700,
    color: '#111',
  }),
  contractTypeDesc: style({
    fontSize: 12,
    color: '#888',
    flex: 1,
  }),
  contractStatusChip: style({
    fontSize: 11,
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: 20,
    flexShrink: 0,
  }),
  contractChipActive: style({
    backgroundColor: '#e0edff',
    color: '#0161de',
  }),
  contractChipExpired: style({
    backgroundColor: '#f5f5f5',
    color: '#9ca3af',
  }),
  contractChipUpcoming: style({
    backgroundColor: '#eff6ff',
    color: '#3b82f6',
  }),
  contractPeriodDates: style({
    fontSize: 12,
    color: '#6b7280',
    lineHeight: '18px',
  }),
  // Work order rows
  workOrderRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: '11px 16px',
    borderBottom: '1px solid #f5f5f5',
  }),
  workOrderRowLast: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: '11px 16px',
  }),
  workOrderTypeTag: style({
    fontSize: 11,
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: 4,
    backgroundColor: '#f0f4ff',
    color: '#3b5bdb',
    flexShrink: 0,
  }),
  workOrderInfo: style({
    flex: 1,
    minWidth: 0,
  }),
  workOrderNo: style({
    fontSize: 13,
    color: '#333',
    fontWeight: 500,
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  workOrderStatus: style({
    fontSize: 12,
    fontWeight: 600,
    flexShrink: 0,
  }),
  workOrderRowClickable: style({
    cursor: 'pointer',
    ':active': { backgroundColor: '#f5f7fa' },
  }),
  workOrderDate: style({
    fontSize: 12,
    color: '#aaa',
    marginTop: 2,
  }),
  workOrderChevron: style({
    color: '#d1d5db',
    fontSize: 18,
    flexShrink: 0,
    marginLeft: 2,
  }),
  // Header: name row with edit button
  headerNameRow: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
  }),
  editNameBtn: style({
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '2px 4px',
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
  }),
  nameEditInput: style({
    flex: 1,
    background: 'rgba(255,255,255,0.15)',
    border: '1px solid rgba(255,255,255,0.4)',
    borderRadius: 6,
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 700,
    padding: '3px 8px',
    outline: 'none',
    minWidth: 0,
  }),
  // Header: expand/collapse toggle
  headerExpandBtn: style({
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '2px 0',
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
  }),
  // Header: expanded info section (EQ, serial)
  headerExpandedInfo: style({
    paddingLeft: 30,
    marginTop: 10,
    paddingTop: 10,
    borderTop: '1px solid rgba(255,255,255,0.15)',
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
  }),
  headerInfoRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  }),
  headerInfoLabel: style({
    fontSize: 11,
    color: 'rgba(255,255,255,0.5)',
    width: 50,
    flexShrink: 0,
  }),
  headerInfoValue: style({
    fontSize: 12,
    color: 'rgba(255,255,255,0.85)',
    letterSpacing: '0.02em',
  }),
  // PM alert banner (between header and tabs)
  pmAlertBanner: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fffbeb',
    borderBottom: '2px solid #f0c040',
    padding: '9px 16px',
    flexShrink: 0,
  }),
  pmAlertIcon: style({ fontSize: 17, flexShrink: 0 }),
  pmAlertText: style({
    flex: 1,
    fontSize: 13,
    color: '#7c4d00',
    fontWeight: 600,
    lineHeight: '18px',
  }),
  pmAlertTabBtn: style({
    background: 'none',
    border: '1px solid #e6a000',
    borderRadius: 20,
    padding: '3px 12px',
    fontSize: 12,
    color: '#7c4d00',
    cursor: 'pointer',
    fontWeight: 600,
    flexShrink: 0,
  }),
  // PM work order rows (inside PM tab)
  pmWorkOrderRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: '11px 16px',
    borderBottom: '1px solid #f5f5f5',
  }),
  pmWorkOrderRowLast: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: '11px 16px',
  }),
  pmWorkOrderDate: style({
    fontSize: 12,
    color: '#aaa',
    marginTop: 2,
  }),
  // PM timeline (保养记录 tab)
  pmScopeNotice: style({
    fontSize: 12,
    color: '#888',
    padding: '8px 16px 4px',
    lineHeight: '18px',
  }),
  pmTimelineRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    padding: '12px 16px',
  }),
  pmTimelineRowBorder: style({
    borderBottom: '1px solid #f5f5f5',
  }),
  pmTimelineDotCol: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: 14,
    flexShrink: 0,
    paddingTop: 3,
  }),
  pmTimelineDot: style({
    width: 10,
    height: 10,
    borderRadius: '50%',
    flexShrink: 0,
  }),
  pmDotCompleted: style({ backgroundColor: '#16a34a' }),
  pmDotActive: style({ backgroundColor: '#0161de' }),
  pmTimelineLine: style({
    flex: 1,
    width: 2,
    backgroundColor: '#e5e7eb',
    marginTop: 4,
    minHeight: 16,
  }),
  pmTimelineContent: style({
    flex: 1,
    minWidth: 0,
    paddingBottom: 2,
  }),
  pmTimelineHeader: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
  }),
  pmTimelineDate: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#222',
    flex: 1,
  }),
  pmTimelineStatus: style({
    fontSize: 12,
    fontWeight: 600,
    flexShrink: 0,
  }),
  pmTimelineWoNo: style({
    fontSize: 12,
    color: '#9ca3af',
  }),
  // Location edit icon in header meta
  headerMetaRow: style({
    paddingLeft: 34,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 0,
  }),
  headerMetaText: style({
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    lineHeight: '18px',
    flex: 1,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  headerMetaEditBtn: style({
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '2px 4px',
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
    opacity: 0.55,
  }),
  headerModelRow: style({
    paddingLeft: 34,
    marginTop: 1,
    marginBottom: 4,
  }),
  headerModelSub: style({
    color: 'rgba(255,255,255,0.55)',
    fontSize: 12,
    lineHeight: '16px',
  }),
  // Location edit panel (below header, above tabs)
  locationEditPanel: style({
    backgroundColor: '#fff',
    borderBottom: '1px solid #e8eaed',
    padding: '12px 16px',
    flexShrink: 0,
  }),
  locationEditRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  }),
  locationEditLabel: style({
    fontSize: 13,
    color: '#888',
    width: 36,
    flexShrink: 0,
  }),
  locationEditInput: style({
    flex: 1,
    border: '1px solid #d0d5dd',
    borderRadius: 8,
    padding: '7px 10px',
    fontSize: 14,
    color: '#111',
    outline: 'none',
    ':focus': { borderColor: '#0161de' },
  }),
  locationEditActions: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'flex-end',
    marginTop: 4,
  }),
  locationEditCancel: style({
    padding: '6px 16px',
    borderRadius: 8,
    border: '1px solid #d0d5dd',
    backgroundColor: '#fff',
    fontSize: 13,
    color: '#555',
    cursor: 'pointer',
  }),
  locationEditSave: style({
    padding: '6px 16px',
    borderRadius: 8,
    border: 'none',
    backgroundColor: '#0161de',
    fontSize: 13,
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 600,
  }),
  // Quick action bar - INSIDE the blue header
  headerActions: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  }),
  headerActionBtnFill: style({
    flex: 3,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: '11px 0',
    borderRadius: 10,
    border: 'none',
    backgroundColor: '#ffffff',
    color: '#0161de',
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
  }),
  headerActionBtnOutline: style({
    flex: 2,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    padding: '11px 0',
    borderRadius: 10,
    border: '1px solid rgba(255,255,255,0.3)',
    backgroundColor: 'transparent',
    color: 'rgba(255,255,255,0.65)',
    fontSize: 13,
    fontWeight: 400,
    cursor: 'pointer',
    textDecoration: 'none',
  }),
  // Quick action bar (standalone white strip) - kept for compat but no longer used
  actionBar: style({
    display: 'none',
  }),
  actionBtnPhone: style({ display: 'none' }),
  actionBtnRepair: style({ display: 'none' }),
  // Date range chips (inside tab content)
  dateRangeRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 6,
    padding: '10px 16px 8px',
    borderBottom: '1px solid #f2f2f2',
    flexShrink: 0,
  }),
  dateRangeChip: style({
    background: 'none',
    border: '1px solid #d0d0d0',
    borderRadius: 100,
    color: '#666',
    fontSize: 12,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 4,
    paddingBottom: 4,
    cursor: 'pointer',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
  }),
  dateRangeChipActive: style({
    backgroundColor: '#0161de',
    borderColor: '#0161de',
    color: '#ffffff',
    fontWeight: 600,
  }),
  tabLoadMoreWrap: style({
    display: 'flex',
    justifyContent: 'center',
    padding: '10px 0 16px',
  }),
  tabLoadMoreBtn: style({
    border: 'none',
    borderRadius: 100,
    backgroundColor: '#e8f2ff',
    color: '#0161de',
    fontSize: 12,
    fontWeight: 600,
    padding: '7px 20px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
};
