import { style } from '@vanilla-extract/css';

export const detailStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    backgroundColor: '#f5f7fa',
  }),
  header: style({
    backgroundColor: '#0161de',
    padding: '14px 16px 16px',
    flexShrink: 0,
  }),
  headerTop: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 6,
  }),
  backBtn: style({
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px 0',
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
  }),
  headerName: style({
    color: '#ffffff',
    fontSize: 17,
    fontWeight: 700,
    lineHeight: '24px',
    flex: 1,
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  headerMeta: style({
    paddingLeft: 34,
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    lineHeight: '18px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  headerChips: style({
    paddingLeft: 34,
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  }),
  chip: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '2px 8px',
    borderRadius: 20,
    fontSize: 11,
    fontWeight: 600,
    lineHeight: '16px',
  }),
  chipSuccess: style({
    background: 'rgba(22,163,74,0.18)',
    color: '#bbf7d0',
    border: '1px solid rgba(22,163,74,0.35)',
  }),
  chipWarning: style({
    background: 'rgba(234,179,8,0.18)',
    color: '#fef08a',
    border: '1px solid rgba(234,179,8,0.35)',
  }),
  chipError: style({
    background: 'rgba(239,68,68,0.18)',
    color: '#fca5a5',
    border: '1px solid rgba(239,68,68,0.35)',
  }),
  chipNeutral: style({
    background: 'rgba(255,255,255,0.15)',
    color: 'rgba(255,255,255,0.85)',
    border: '1px solid rgba(255,255,255,0.25)',
  }),
  chipActive: style({
    background: 'rgba(96,165,250,0.25)',
    color: '#bfdbfe',
    border: '1px solid rgba(96,165,250,0.4)',
  }),
  scrollContent: style({
    flex: 1,
    overflowY: 'auto',
    scrollbarWidth: 'none',
    '::-webkit-scrollbar': { display: 'none' },
    padding: '12px 0 24px',
  }),
  // Alert banners (before sections)
  alertBannerWarn: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    margin: '0 16px 10px',
    backgroundColor: '#fff8e6',
    border: '1px solid #f0c843',
    borderRadius: 10,
    padding: '10px 14px',
  }),
  alertBannerDanger: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    margin: '0 16px 10px',
    backgroundColor: '#fff1f0',
    border: '1px solid #ffb3b3',
    borderRadius: 10,
    padding: '10px 14px',
  }),
  alertBannerInfo: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    margin: '0 16px 10px',
    backgroundColor: '#f0f6ff',
    border: '1px solid #b3d1ff',
    borderRadius: 10,
    padding: '10px 14px',
  }),
  alertText: style({
    fontSize: 13,
    lineHeight: '18px',
    flex: 1,
    color: '#444',
  }),
  // Section cards
  section: style({
    margin: '0 16px 10px',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
  }),
  sectionHead: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px 8px',
    borderBottom: '1px solid #f2f2f2',
  }),
  sectionTitle: style({
    fontSize: 12,
    fontWeight: 600,
    color: '#888',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  }),
  daysChip: style({
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 3,
    paddingBottom: 3,
    fontSize: 12,
    fontWeight: 600,
  }),
  chipGood: style({ backgroundColor: '#e8f7ef', color: '#0a7c3e' }),
  chipWarn: style({ backgroundColor: '#fff4e0', color: '#7a4800' }),
  chipDanger: style({ backgroundColor: '#ffefef', color: '#c0392b' }),
  // Info rows
  infoRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '11px 16px',
    gap: 8,
    borderBottom: '1px solid #f5f5f5',
  }),
  infoRowLast: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '11px 16px',
    gap: 8,
  }),
  infoLabel: style({
    fontSize: 13,
    color: '#999',
    width: 60,
    flexShrink: 0,
    lineHeight: '20px',
  }),
  infoValue: style({
    fontSize: 14,
    color: '#222',
    lineHeight: '20px',
    flex: 1,
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  infoValueAccent: style({
    fontSize: 14,
    color: '#00126e',
    fontWeight: 700,
    lineHeight: '20px',
    flex: 1,
  }),
  // Service status row
  serviceRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
    padding: '12px 16px',
  }),
  serviceDot: style({
    width: 10,
    height: 10,
    borderRadius: '50%',
    backgroundColor: '#0072db',
    flexShrink: 0,
    marginTop: 5,
  }),
  serviceInfo: style({
    flex: 1,
    minWidth: 0,
  }),
  serviceLabel: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#222',
    lineHeight: '20px',
  }),
  serviceDate: style({
    fontSize: 13,
    color: '#888',
    lineHeight: '18px',
    marginTop: 2,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  serviceEngineer: style({
    fontSize: 13,
    color: '#0072db',
    lineHeight: '18px',
    marginTop: 2,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  // History items
  historyItem: style({
    display: 'flex',
    flexDirection: 'row',
    padding: '10px 16px',
    gap: 12,
    alignItems: 'flex-start',
    borderBottom: '1px solid #f5f5f5',
  }),
  historyItemLast: style({
    display: 'flex',
    flexDirection: 'row',
    padding: '10px 16px',
    gap: 12,
    alignItems: 'flex-start',
  }),
  historyDot: style({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: '#bbb',
    flexShrink: 0,
    marginTop: 6,
  }),
  historyLabel: style({
    fontSize: 14,
    color: '#444',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    flex: 1,
  }),
  historyMeta: style({
    fontSize: 12,
    color: '#999',
    lineHeight: '18px',
    marginTop: 2,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  // Tab bar
  tabBar: style({
    display: 'flex',
    flexDirection: 'row',
    background: '#0161de',
    flexShrink: 0,
  }),
  tabBtn: style({
    flex: 1,
    background: 'none',
    border: 'none',
    padding: '10px 0',
    fontSize: 14,
    color: 'rgba(255,255,255,0.65)',
    cursor: 'pointer',
    position: 'relative',
    fontWeight: 500,
    letterSpacing: '0.01em',
  }),
  tabBtnActive: style({
    color: '#fff',
    fontWeight: 700,
    ':after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      bottom: 0,
      left: '50%',
      transform: 'translateX(-50%)',
      width: 32,
      height: 3,
      borderRadius: '3px 3px 0 0',
      background: '#fff',
    },
  }),
  // Tab content area
  tabContent: style({
    flex: 1,
    overflowY: 'auto',
    scrollbarWidth: 'none',
    '::-webkit-scrollbar': { display: 'none' },
    padding: '12px 0 24px',
  }),
  // Repair history note banner
  noteBanner: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    margin: '0 16px 10px',
    backgroundColor: '#fffbeb',
    border: '1px solid #fee685',
    borderRadius: 10,
    padding: '10px 14px',
  }),
  noteBannerText: style({
    fontSize: 13,
    color: '#bb4d00',
    lineHeight: '20px',
    flex: 1,
  }),
  // Repair history card items
  repairHistoryCard: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    margin: '0 16px 8px',
    background: '#fff',
    borderRadius: 12,
    padding: '14px 12px 14px 16px',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
    cursor: 'pointer',
    border: '1px solid #f0f0f0',
  }),
  repairHistoryLeft: style({
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  }),
  repairHistoryTopRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  }),
  repairHistoryId: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#0a0a0a',
  }),
  repairHistoryStatusTag: style({
    fontSize: 11,
    padding: '2px 7px',
    borderRadius: 4,
    fontWeight: 600,
    flexShrink: 0,
  }),
  repairHistoryStatusInService: style({
    background: '#e8f0fe',
    color: '#0072db',
  }),
  repairHistoryStatusCompleted: style({
    background: '#f0fdf4',
    color: '#16a34a',
  }),
  repairHistoryStatusCancelled: style({
    background: '#f5f5f5',
    color: '#9ca3af',
  }),
  repairHistoryMeta: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  }),
  repairHistoryMetaRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    fontSize: 12,
    color: '#9ca3af',
  }),
  repairHistoryMetaLabel: style({
    flexShrink: 0,
    width: 56,
  }),
  repairHistoryDesc: style({
    fontSize: 13,
    color: '#374151',
    lineHeight: '18px',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  repairHistoryChevron: style({
    color: '#d1d5db',
    fontSize: 20,
    flexShrink: 0,
  }),
  emptyHistory: style({
    textAlign: 'center',
    padding: '48px 24px',
    color: '#9ca3af',
    fontSize: 14,
  }),
};
