import { style } from '@vanilla-extract/css';

export const deviceListPageStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    maxWidth: 375,
    minHeight: '100vh',
    margin: '0 auto',
    overflowX: 'hidden',
  }),
  topBar: style({
    width: '100%',
    backgroundColor: '#0161de',
    padding: '12px 16px 16px',
    flexShrink: 0,
  }),
  topBarTitle: style({
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 600,
    lineHeight: '26px',
  }),
  topBarSub: style({
    color: 'rgba(255,255,255,0.75)',
    fontSize: 13,
    lineHeight: '20px',
    marginTop: 2,
  }),
  statsRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  }),
  statCard: style({
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 10,
    padding: '8px 10px',
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  }),
  statNumber: style({
    color: '#ffffff',
    fontSize: 22,
    fontWeight: 700,
    lineHeight: '28px',
  }),
  statLabel: style({
    color: 'rgba(255,255,255,0.75)',
    fontSize: 11,
    lineHeight: '16px',
  }),
  content: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    paddingBottom: 16,
  }),
  searchRow: style({
    padding: '12px 16px 0',
  }),
  filterRow: style({
    padding: '8px 0 0',
    overflowX: 'auto',
  }),
  chipGroup: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    padding: '0 16px',
    paddingBottom: 4,
  }),
  chip: style({
    background: 'none',
    border: '1px solid #d0d0d0',
    borderRadius: 100,
    color: '#555',
    fontSize: 13,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 6,
    paddingBottom: 6,
    cursor: 'pointer',
    fontFamily: 'inherit',
    flexShrink: 0,
    whiteSpace: 'nowrap',
  }),
  chipActive: style({
    backgroundColor: '#0161de',
    borderColor: '#0161de',
    color: '#ffffff',
    fontWeight: 600,
  }),
  listSection: style({
    padding: '12px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  }),
  sectionHeader: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 4,
  }),
  bottomBarWrapper: style({
    position: 'fixed',
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '100%',
    maxWidth: 375,
    zIndex: 100,
  }),
};
