import { style } from '@vanilla-extract/css';

export const deviceListPageStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    maxWidth: 375,
    minHeight: '100vh',
    margin: '0 auto',
    overflowX: 'hidden',
    backgroundColor: '#F0F9FF',
  }),
  topBar: style({
    width: '100%',
    backgroundColor: '#0161de',
    padding: '12px 16px 16px',
    flexShrink: 0,
  }),
  topBarTitle: style({
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 600,
    lineHeight: '26px',
  }),
  topBarHeaderRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  }),
  scanBtnTop: style({
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 32,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 16,
    border: 'none',
    backgroundColor: '#ffffff',
    color: '#0161de',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
  }),
  topBarSub: style({
    color: 'rgba(255,255,255,0.75)',
    fontSize: 13,
    lineHeight: '20px',
    marginTop: 2,
  }),
  statsScrollRow: style({
    overflowX: 'auto',
    marginTop: 14,
    marginLeft: -16,
    marginRight: -16,
    paddingLeft: 16,
    scrollbarWidth: 'none',
  }),
  statsRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    paddingRight: 16,
    width: 'max-content',
  }),
  statCard: style({
    minWidth: 70,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 10,
    padding: '8px 10px',
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    cursor: 'pointer',
    border: 'none',
    fontFamily: 'inherit',
    textAlign: 'left',
    color: 'rgba(255,255,255,0.9)',
  }),
  statCardActive: style({
    backgroundColor: 'rgba(255,255,255,0.95)',
    color: '#0161de',
  }),
  statNumber: style({
    color: 'inherit',
    fontSize: 22,
    fontWeight: 700,
    lineHeight: '28px',
  }),
  statLabel: style({
    color: 'inherit',
    fontSize: 11,
    lineHeight: '16px',
    opacity: 0.8,
  }),
  content: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    paddingBottom: 16,
  }),
  searchFilterRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    padding: '12px 16px',
    alignItems: 'center',
    backgroundColor: 'transparent',
    flexShrink: 0,
  }),
  searchBox: style({
    width: 140,
    flexShrink: 0,
  }),
  chipScroll: style({
    flex: 1,
    minWidth: 0,
    overflowX: 'auto',
    scrollbarWidth: 'none',
    WebkitMaskImage: 'linear-gradient(to right, #000 calc(100% - 22px), transparent)',
    maskImage: 'linear-gradient(to right, #000 calc(100% - 22px), transparent)',
  }),
  chipGroupInline: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    width: 'max-content',
    paddingRight: 22,
  }),
  antiCounterfeitSectionBanner: style({
    margin: '12px 16px 8px',
    padding: '12px 14px',
    borderRadius: 12,
    backgroundColor: '#f0f7ff',
    border: '1px solid #d0e8ff',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    width: 'calc(100% - 32px)',
    fontFamily: 'inherit',
    textAlign: 'left',
  }),
  antiCounterfeitBannerIcon: style({
    flexShrink: 0,
    width: 32,
    height: 32,
    borderRadius: '50%',
    backgroundColor: '#0161de',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  antiCounterfeitBannerContent: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  }),
  antiCounterfeitBannerTitle: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#0161de',
  }),
  antiCounterfeitBannerDesc: style({
    fontSize: 11,
    color: '#667',
  }),
  filterRow: style({
    padding: '8px 0 0',
    overflowX: 'auto',
  }),
  chipGroup: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    padding: '0 16px',
    paddingBottom: 4,
  }),
  chip: style({
    backgroundColor: '#ffffff',
    border: '1px solid #d8e0ea',
    borderRadius: 100,
    color: '#3a4250',
    fontSize: 14,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 9,
    paddingBottom: 9,
    cursor: 'pointer',
    fontFamily: 'inherit',
    flexShrink: 0,
    whiteSpace: 'nowrap',
  }),
  chipActive: style({
    backgroundColor: '#0161de',
    borderColor: '#0161de',
    color: '#ffffff',
    fontWeight: 600,
  }),
  pmPlanHint: style({
    fontSize: 11,
    lineHeight: '16px',
    color: '#8a94a6',
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 2,
  }),
  pmDatePicker: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '6px 0 6px 16px',
    borderTop: '1px solid #f0f0f0',
    overflow: 'hidden',
  }),
  pmYearPart: style({
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    paddingRight: 10,
    borderRight: '1px solid #e5e7eb',
    marginRight: 8,
  }),
  pmYearArrow: style({
    width: 22,
    height: 26,
    background: 'none',
    border: 'none',
    color: '#0161de',
    fontSize: 15,
    cursor: 'pointer',
    fontFamily: 'inherit',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  }),
  pmYearLabel: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#374151',
    whiteSpace: 'nowrap',
  }),
  pmMonthStrip: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    gap: 5,
    overflowX: 'auto',
    paddingRight: 16,
    alignItems: 'center',
    scrollbarWidth: 'none',
  }),
  pmMonthStripItem: style({
    flexShrink: 0,
    height: 26,
    paddingLeft: 10,
    paddingRight: 10,
    border: '1px solid #e5e7eb',
    borderRadius: 14,
    background: 'none',
    color: '#4b5563',
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
  }),
  pmMonthStripItemActive: style({
    backgroundColor: '#0161de',
    borderColor: '#0161de',
    color: '#ffffff',
    fontWeight: 600,
  }),
  pmMonthStripItemToday: style({
    borderColor: '#0161de',
    color: '#0161de',
  }),
  pmUltrasoundNote: style({
    fontSize: 11,
    lineHeight: '16px',
    color: '#8a94a6',
    backgroundColor: '#f7f8fa',
    borderRadius: 6,
    padding: '6px 10px',
    marginBottom: 2,
  }),
  listSection: style({
    padding: '12px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  }),
  sectionHeader: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 4,
  }),
  bottomBarWrapper: style({
    position: 'fixed',
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '100%',
    maxWidth: 375,
    zIndex: 100,
  }),
  campusSelectorRow: style({
    position: 'relative',
    marginTop: 8,
  }),
  campusSelectorBtn: style({
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    background: 'rgba(255,255,255,0.18)',
    border: '1px solid rgba(255,255,255,0.35)',
    borderRadius: 8,
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 500,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 5,
    paddingBottom: 5,
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  campusSelectorSingle: style({
    display: 'inline-block',
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 500,
  }),
  campusChevron: style({
    fontSize: 10,
    opacity: 0.8,
  }),
  campusBackdrop: style({
    position: 'fixed',
    inset: 0,
    zIndex: 40,
  }),
  campusDropdown: style({
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: 0,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    overflow: 'hidden',
    zIndex: 50,
    minWidth: 160,
    maxWidth: 280,
  }),
  campusDropdownItem: style({
    display: 'block',
    width: '100%',
    padding: '11px 14px',
    background: 'none',
    border: 'none',
    fontSize: 14,
    color: '#333',
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
  }),
  campusDropdownItemActive: style({
    backgroundColor: '#e8f2ff',
    color: '#0161de',
    fontWeight: 600,
  }),
  loadMoreWrap: style({
    paddingTop: 8,
    paddingBottom: 8,
    display: 'flex',
    justifyContent: 'center',
  }),
  loadMoreBtn: style({
    background: 'none',
    border: '1px solid #d0d0d0',
    borderRadius: 100,
    color: '#0161de',
    fontSize: 13,
    fontWeight: 500,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 8,
    paddingBottom: 8,
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  sortBtnWrap: style({
    position: 'relative',
  }),
  sortBtn: style({
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    background: 'none',
    border: 'none',
    color: '#0161de',
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    fontFamily: 'inherit',
    padding: '2px 0',
  }),
  sortBackdrop: style({
    position: 'fixed',
    inset: 0,
    zIndex: 40,
  }),
  sortDropdown: style({
    position: 'absolute',
    top: 'calc(100% + 4px)',
    right: 0,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    overflow: 'hidden',
    zIndex: 50,
    minWidth: 110,
    boxShadow: '0 4px 16px rgba(0,0,0,0.12)',
  }),
  sortDropdownItem: style({
    display: 'block',
    width: '100%',
    padding: '10px 14px',
    background: 'none',
    border: 'none',
    fontSize: 13,
    color: '#333',
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
  }),
  sortDropdownItemActive: style({
    backgroundColor: '#e8f2ff',
    color: '#0161de',
    fontWeight: 600,
  }),
};
