import { style } from '@vanilla-extract/css';

export const infoTabStyles = {
  // ── Status alert cards ─────────────────────────────────────────────
  noTopPad: style({
    paddingTop: 0,
  }),
  statusSection: style({
    backgroundColor: '#ffffff',
  }),
  statusCard: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '11px 16px 11px 13px',
    borderBottom: '1px solid #f0f0f0',
    gap: 12,
    cursor: 'pointer',
    borderLeft: '3px solid transparent',
    selectors: { '&:active': { backgroundColor: '#fafafa' } },
  }),
  statusCardStatic: style({
    cursor: 'default',
  }),
  statusCardDanger: style({ borderLeftColor: '#e53935' }),
  statusCardWarning: style({ borderLeftColor: '#d14600' }),
  statusCardCaution: style({ borderLeftColor: '#806a00' }),
  statusCardNeutral: style({ borderLeftColor: '#90a4ae' }),
  statusCardActive: style({ borderLeftColor: '#0092fa' }),
  statusContent: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
  }),
  statusBadge: style({
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 4,
    padding: '1px 6px',
    display: 'inline-block',
    alignSelf: 'flex-start',
    letterSpacing: '0.02em',
  }),
  statusBadgeDanger: style({ backgroundColor: '#ffebee', color: '#c62828' }),
  statusBadgeWarning: style({ backgroundColor: '#ffe0c8', color: '#c24100' }),
  statusBadgeCaution: style({ backgroundColor: '#fff7d1', color: '#806a00' }),
  statusBadgeNeutral: style({ backgroundColor: '#eceff1', color: '#455a64' }),
  statusBadgeActive: style({ backgroundColor: '#f0f9ff', color: '#006ebd' }),
  statusDesc: style({ fontSize: 13, color: '#666', lineHeight: 1.4 }),
  statusArrow: style({ fontSize: 14, color: '#bbb', flexShrink: 0 }),
  statusEmpty: style({
    padding: '16px 16px',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  }),
  statusEmptyDot: style({
    width: 7,
    height: 7,
    borderRadius: '50%',
    backgroundColor: '#4caf50',
    flexShrink: 0,
  }),
  statusEmptyText: style({ fontSize: 14, color: '#999' }),
  // ── Section headers & dividers ─────────────────────────────────────
  sectionHeader: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#1a1a1a',
    padding: '12px 16px 8px',
    letterSpacing: '0.01em',
  }),
  sectionHeaderRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px 8px',
  }),
  sectionHeaderTitle: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#1a1a1a',
    letterSpacing: '0.01em',
  }),
  phoneLink: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    fontSize: 13,
    color: '#0161de',
    textDecoration: 'none',
    flexShrink: 0,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    fontFamily: 'inherit',
  }),
  addEntry: style({
    flex: 1,
    textAlign: 'left',
    fontSize: 14,
    color: '#0161de',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    fontFamily: 'inherit',
  }),
  modelValueCol: style({
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  }),
  modelName: style({
    fontSize: 14,
    color: '#1a1a1a',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  modelNote: style({
    fontSize: 12,
    color: '#888',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  editAreaLabel: style({
    display: 'block',
    fontSize: 13,
    color: '#666',
    marginBottom: 8,
  }),
  infoCard: style({
    margin: '0 16px 12px',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(0,0,0,0.07)',
  }),
  statusAllGood: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: '12px 16px',
    borderBottom: '1px solid #f0f0f0',
  }),
  statusAllGoodDot: style({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: '#22c55e',
    flexShrink: 0,
  }),
  statusAllGoodText: style({
    fontSize: 14,
    color: '#15803d',
    fontWeight: 500,
  }),
  divider: style({
    height: 8,
    backgroundColor: '#f5f5f7',
    borderTop: '1px solid #ebebeb',
    borderBottom: '1px solid #ebebeb',
  }),
  locationGroupDivider: style({
    padding: '7px 16px 6px',
    backgroundColor: '#f7f8fc',
    borderTop: '1px solid #ebebeb',
    borderBottom: '1px solid #ebebeb',
    fontSize: 11,
    fontWeight: 600,
    color: '#aaa',
    letterSpacing: '0.05em',
  }),
  // ── Device info rows ───────────────────────────────────────────────
  row: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '11px 16px',
    borderBottom: '1px solid #f0f0f0',
    gap: 12,
    minHeight: 44,
  }),
  label: style({
    fontSize: 13,
    color: '#999',
    width: 68,
    flexShrink: 0,
  }),
  value: style({ fontSize: 14, color: '#1a1a1a', flex: 1 }),
  valueMuted: style({ fontSize: 14, color: '#bbb', flex: 1 }),
  editBtn: style({
    fontSize: 12,
    color: '#0161de',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px 0',
    flexShrink: 0,
  }),
  // ── Edit mode ──────────────────────────────────────────────────────
  editArea: style({
    padding: '14px 16px 16px',
    backgroundColor: '#f7f8fc',
    borderBottom: '1px solid #e8e8e8',
  }),
  editRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  }),
  editLabel: style({ fontSize: 13, color: '#666', width: 40, flexShrink: 0 }),
  editInput: style({
    flex: 1,
    fontSize: 14,
    padding: '8px 10px',
    border: '1.5px solid #d8d8d8',
    borderRadius: 6,
    outline: 'none',
    background: 'white',
  }),
  editInputFull: style({
    width: '100%',
    fontSize: 14,
    padding: '8px 10px',
    border: '1.5px solid #d8d8d8',
    borderRadius: 6,
    outline: 'none',
    background: 'white',
    marginBottom: 12,
    boxSizing: 'border-box',
  }),
  editActions: style({
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 4,
  }),
  btnCancel: style({
    fontSize: 13,
    padding: '6px 16px',
    borderRadius: 6,
    border: '1px solid #ddd',
    background: 'white',
    color: '#555',
    cursor: 'pointer',
  }),
  btnSave: style({
    fontSize: 13,
    padding: '6px 16px',
    borderRadius: 6,
    border: 'none',
    background: '#0161de',
    color: 'white',
    cursor: 'pointer',
  }),
  // ── Notes section ──────────────────────────────────────────────────
  noteHint: style({
    fontSize: 12,
    color: '#bbb',
    padding: '0 16px 12px',
    lineHeight: 1.5,
  }),
  localNote: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 7,
    margin: '4px 16px 20px',
    padding: '11px 12px',
    backgroundColor: '#eef3fe',
    borderRadius: 10,
  }),
  localNoteIcon: style({
    color: '#0161de',
    flexShrink: 0,
    marginTop: 1,
  }),
  localNoteText: style({
    flex: 1,
    fontSize: 12,
    color: '#5b6b86',
    lineHeight: '18px',
  }),
  dialogOverlay: style({
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 40px',
    zIndex: 1000,
  }),
  dialogCard: style({
    width: '100%',
    maxWidth: 300,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  }),
  dialogBody: style({
    padding: '24px 20px 20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 6,
  }),
  dialogTitle: style({
    fontSize: 15,
    fontWeight: 600,
    color: '#1a1a1a',
  }),
  dialogNumber: style({
    fontSize: 23,
    fontWeight: 700,
    color: '#0161de',
    letterSpacing: '0.03em',
  }),
  dialogSub: style({
    fontSize: 12,
    color: '#999',
    marginTop: 2,
  }),
  dialogActions: style({
    display: 'flex',
    flexDirection: 'row',
    borderTop: '1px solid #ececec',
  }),
  dialogBtn: style({
    flex: 1,
    padding: '13px 0',
    textAlign: 'center',
    fontSize: 16,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    textDecoration: 'none',
  }),
  dialogBtnCancel: style({
    color: '#666',
    borderRight: '1px solid #ececec',
  }),
  dialogBtnCall: style({
    color: '#0161de',
    fontWeight: 600,
  }),
};
