import { style } from '@vanilla-extract/css';

export const infoTabStyles = {
  // ── Status alert cards ─────────────────────────────────────────────
  statusCard: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '11px 16px 11px 13px',
    borderBottom: '1px solid #f0f0f0',
    gap: 12,
    cursor: 'pointer',
    borderLeft: '3px solid transparent',
    selectors: { '&:active': { backgroundColor: '#fafafa' } },
  }),
  statusCardStatic: style({
    cursor: 'default',
  }),
  statusCardDanger: style({ borderLeftColor: '#e53935' }),
  statusCardWarning: style({ borderLeftColor: '#f9a825' }),
  statusCardNeutral: style({ borderLeftColor: '#90a4ae' }),
  statusCardActive: style({ borderLeftColor: '#1565c0' }),
  statusContent: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
  }),
  statusBadge: style({
    fontSize: 11,
    fontWeight: 600,
    borderRadius: 4,
    padding: '1px 6px',
    display: 'inline-block',
    alignSelf: 'flex-start',
    letterSpacing: '0.02em',
  }),
  statusBadgeDanger: style({ backgroundColor: '#ffebee', color: '#c62828' }),
  statusBadgeWarning: style({ backgroundColor: '#fff8e1', color: '#e65100' }),
  statusBadgeNeutral: style({ backgroundColor: '#eceff1', color: '#455a64' }),
  statusBadgeActive: style({ backgroundColor: '#e3f2fd', color: '#1565c0' }),
  statusDesc: style({ fontSize: 13, color: '#666', lineHeight: 1.4 }),
  statusArrow: style({ fontSize: 14, color: '#bbb', flexShrink: 0 }),
  statusEmpty: style({
    padding: '16px 16px',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  }),
  statusEmptyDot: style({
    width: 7,
    height: 7,
    borderRadius: '50%',
    backgroundColor: '#4caf50',
    flexShrink: 0,
  }),
  statusEmptyText: style({ fontSize: 14, color: '#999' }),
  // ── Section headers & dividers ─────────────────────────────────────
  sectionHeader: style({
    fontSize: 11,
    fontWeight: 600,
    color: '#999',
    padding: '14px 16px 8px',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  }),
  divider: style({
    height: 8,
    backgroundColor: '#f5f5f7',
    borderTop: '1px solid #ebebeb',
    borderBottom: '1px solid #ebebeb',
  }),
  // ── Device info rows ───────────────────────────────────────────────
  row: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '11px 16px',
    borderBottom: '1px solid #f0f0f0',
    gap: 12,
    minHeight: 44,
  }),
  label: style({
    fontSize: 13,
    color: '#999',
    width: 68,
    flexShrink: 0,
  }),
  value: style({ fontSize: 14, color: '#1a1a1a', flex: 1 }),
  valueMuted: style({ fontSize: 14, color: '#bbb', flex: 1 }),
  editBtn: style({
    fontSize: 12,
    color: '#0161de',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px 0',
    flexShrink: 0,
  }),
  // ── Edit mode ──────────────────────────────────────────────────────
  editArea: style({
    padding: '14px 16px 16px',
    backgroundColor: '#f7f8fc',
    borderBottom: '1px solid #e8e8e8',
  }),
  editRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  }),
  editLabel: style({ fontSize: 13, color: '#666', width: 40, flexShrink: 0 }),
  editInput: style({
    flex: 1,
    fontSize: 14,
    padding: '8px 10px',
    border: '1.5px solid #d8d8d8',
    borderRadius: 6,
    outline: 'none',
    background: 'white',
  }),
  editInputFull: style({
    width: '100%',
    fontSize: 14,
    padding: '8px 10px',
    border: '1.5px solid #d8d8d8',
    borderRadius: 6,
    outline: 'none',
    background: 'white',
    marginBottom: 12,
    boxSizing: 'border-box',
  }),
  editActions: style({
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 4,
  }),
  btnCancel: style({
    fontSize: 13,
    padding: '6px 16px',
    borderRadius: 6,
    border: '1px solid #ddd',
    background: 'white',
    color: '#555',
    cursor: 'pointer',
  }),
  btnSave: style({
    fontSize: 13,
    padding: '6px 16px',
    borderRadius: 6,
    border: 'none',
    background: '#0161de',
    color: 'white',
    cursor: 'pointer',
  }),
  // ── Notes section ──────────────────────────────────────────────────
  noteHint: style({
    fontSize: 12,
    color: '#bbb',
    padding: '0 16px 12px',
    lineHeight: 1.5,
  }),
  sectionNote: style({
    fontSize: 11,
    color: '#c8c8c8',
    padding: '10px 16px 16px',
    lineHeight: 1.5,
  }),
};
