import { style } from '@vanilla-extract/css';

export const homePageStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: '100%',
    overflowX: 'hidden',
    backgroundColor: '#f5f7fa',
  }),
  topBar: style({
    backgroundColor: '#0161de',
    padding: '14px 16px 14px',
    flexShrink: 0,
  }),
  topBarTitle: style({
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 700,
    lineHeight: '28px',
  }),
  topBarSub: style({
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    lineHeight: '18px',
    marginTop: 2,
  }),
  scanRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: '10px 16px',
    borderBottom: '1px solid #f0f0f0',
    flexShrink: 0,
    gap: 8,
  }),
  scanLabel: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#0072db',
    lineHeight: '20px',
  }),
  scanSecondary: style({
    fontSize: 13,
    color: '#aaa',
    lineHeight: '20px',
    marginLeft: 'auto',
    whiteSpace: 'nowrap',
  }),
  filterRow: style({
    overflowX: 'auto',
    scrollbarWidth: 'none',
    '::-webkit-scrollbar': { display: 'none' },
    backgroundColor: '#ffffff',
    padding: '8px 0 8px',
    borderBottom: '1px solid #f0f0f0',
    flexShrink: 0,
  }),
  chipGroup: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    paddingLeft: 16,
    paddingRight: 16,
    width: 'max-content',
  }),
  chip: style({
    borderRadius: 100,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 5,
    paddingBottom: 5,
    fontSize: 13,
    fontWeight: 500,
    border: '1px solid #d0d7e0',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    backgroundColor: '#ffffff',
    color: '#444',
    fontFamily: 'inherit',
  }),
  chipActive: style({
    backgroundColor: '#0072db',
    borderColor: '#0072db',
    color: '#ffffff',
    fontWeight: 600,
  }),
  listSection: style({
    padding: '10px 16px 16px',
    display: 'flex',
    flexDirection: 'column',
  }),
  emptyState: style({
    padding: '40px 0',
    textAlign: 'center',
  }),
};
