import { style } from '@vanilla-extract/css';

export const detailStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: '100%',
    backgroundColor: '#f5f7fa',
  }),
  header: style({
    backgroundColor: '#0161de',
    padding: '14px 16px 24px',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
  }),
  backBtn: style({
    background: 'none',
    border: 'none',
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
    padding: 0,
    marginBottom: 14,
    cursor: 'pointer',
    fontFamily: 'inherit',
    alignSelf: 'flex-start',
  }),
  headerBadge: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    borderRadius: 100,
    padding: '3px 10px',
    fontSize: 12,
    fontWeight: 600,
    color: '#ffffff',
    marginBottom: 10,
    alignSelf: 'flex-start',
  }),
  headerTitle: style({
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 700,
    lineHeight: '28px',
    marginBottom: 4,
  }),
  headerMeta: style({
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    marginTop: 4,
  }),
  body: style({
    flex: 1,
    padding: '20px 16px 40px',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    overflowY: 'auto',
  }),
  descCard: style({
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: '14px 16px',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
  }),
  descText: style({
    fontSize: 14,
    color: '#444',
    lineHeight: '22px',
  }),
  sectionLabel: style({
    fontSize: 12,
    fontWeight: 600,
    color: '#999',
    letterSpacing: '0.05em',
    marginBottom: 8,
  }),
  deviceListCard: style({
    backgroundColor: '#ffffff',
    borderRadius: 12,
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
  }),
  deviceItem: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: '14px 16px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
    gap: 12,
  }),
  deviceItemBorder: style({
    borderBottom: '1px solid #f2f2f2',
  }),
  deviceLeft: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    flex: 1,
    minWidth: 0,
  }),
  deviceName: style({
    fontSize: 15,
    fontWeight: 600,
    color: '#1a1a1a',
    lineHeight: '20px',
  }),
  deviceDept: style({
    fontSize: 13,
    color: '#888',
    lineHeight: '18px',
  }),
  deviceSummaryDanger: style({
    fontSize: 13,
    color: '#c0392b',
    lineHeight: '18px',
    fontWeight: 500,
  }),
  deviceSummaryWarn: style({
    fontSize: 13,
    color: '#7a4800',
    lineHeight: '18px',
    fontWeight: 500,
  }),
  deviceSummaryNeutral: style({
    fontSize: 13,
    color: '#555',
    lineHeight: '18px',
  }),
  chevron: style({
    color: '#0161de',
    fontSize: 22,
    fontWeight: 300,
    flexShrink: 0,
    lineHeight: 1,
  }),
  // Single message body (for non-aggregated landing page)
  singleAction: style({
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: '16px',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  }),
  goToDeviceBtn: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: '12px 14px',
    backgroundColor: '#f0f5ff',
    border: '1px solid #d0e0ff',
    borderRadius: 10,
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
  }),
  goToDeviceName: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#0161de',
  }),
  goToDeviceChevron: style({
    color: '#0161de',
    fontSize: 18,
  }),
};
