import { style } from '@vanilla-extract/css';

export const detailStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: '100%',
    backgroundColor: '#f5f7fa',
  }),
  header: style({
    backgroundColor: '#0161de',
    padding: '14px 16px 24px',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
  }),
  backBtn: style({
    background: 'none',
    border: 'none',
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
    padding: 0,
    marginBottom: 14,
    cursor: 'pointer',
    fontFamily: 'inherit',
    alignSelf: 'flex-start',
  }),
  headerBadge: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    borderRadius: 100,
    padding: '3px 10px',
    fontSize: 12,
    fontWeight: 600,
    color: '#ffffff',
    marginBottom: 10,
    alignSelf: 'flex-start',
  }),
  headerTitle: style({
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 700,
    lineHeight: '28px',
    marginBottom: 4,
  }),
  headerMeta: style({
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    marginTop: 4,
  }),
  body: style({
    flex: 1,
    padding: '20px 16px 40px',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    overflowY: 'auto',
  }),
  descCard: style({
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: '14px 16px',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
  }),
  descText: style({
    fontSize: 14,
    color: '#444',
    lineHeight: '22px',
  }),
  sectionLabel: style({
    fontSize: 12,
    fontWeight: 600,
    color: '#999',
    letterSpacing: '0.05em',
    marginBottom: 8,
  }),
  deviceListCard: style({
    backgroundColor: '#ffffff',
    borderRadius: 12,
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
  }),
  deviceItem: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: '14px 16px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
    gap: 12,
  }),
  deviceItemBorder: style({
    borderBottom: '1px solid #f2f2f2',
  }),
  expandDevicesBtn: style({
    display: 'block',
    width: '100%',
    padding: '12px 16px',
    background: '#f7f9ff',
    border: 'none',
    borderTop: '1px solid #eef1f8',
    color: '#0161de',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'center',
  }),
  deviceLeft: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    flex: 1,
    minWidth: 0,
  }),
  deviceName: style({
    fontSize: 15,
    fontWeight: 600,
    color: '#1a1a1a',
    lineHeight: '20px',
  }),
  deviceDept: style({
    fontSize: 13,
    color: '#888',
    lineHeight: '18px',
  }),
  deviceSummaryDanger: style({
    fontSize: 13,
    color: '#c0392b',
    lineHeight: '18px',
    fontWeight: 500,
  }),
  deviceSummaryWarn: style({
    fontSize: 13,
    color: '#7a4800',
    lineHeight: '18px',
    fontWeight: 500,
  }),
  deviceSummaryNeutral: style({
    fontSize: 13,
    color: '#555',
    lineHeight: '18px',
  }),
  chevron: style({
    color: '#0161de',
    fontSize: 22,
    fontWeight: 300,
    flexShrink: 0,
    lineHeight: 1,
  }),
  // Single message body (for non-aggregated landing page)
  singleAction: style({
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: '16px',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  }),
  goToDeviceBtn: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: '12px 14px',
    backgroundColor: '#f0f5ff',
    border: '1px solid #d0e0ff',
    borderRadius: 10,
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
  }),
  goToDeviceName: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#0161de',
  }),
  goToDeviceChevron: style({
    color: '#0161de',
    fontSize: 18,
  }),
  workOrderCard: style({
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: '16px',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  }),
  workOrderTopRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  }),
  workOrderTypeBadge: style({
    fontSize: 11,
    fontWeight: 600,
    color: '#0a7c3e',
    backgroundColor: '#e8f7ef',
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 3,
    paddingBottom: 3,
    borderRadius: 6,
    lineHeight: '16px',
  }),
  workOrderOrderNo: style({
    fontSize: 12,
    color: '#666',
    lineHeight: '16px',
  }),
  workOrderDeviceRow: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    marginTop: 2,
  }),
  workOrderDeviceMeta: style({
    fontSize: 12,
    color: '#888',
    lineHeight: '17px',
  }),
  workOrderReqTime: style({
    fontSize: 12,
    color: '#888',
    lineHeight: '17px',
    paddingTop: 8,
    borderTop: '1px solid #f0f0f0',
  }),
  signBtnFull: style({
    backgroundColor: '#0161de',
    border: 'none',
    borderRadius: 8,
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 600,
    paddingTop: 13,
    paddingBottom: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
    width: '100%',
    textAlign: 'center',
  }),
  workOrderLeft: style({ display: 'flex', flexDirection: 'column', gap: 3, flex: 1, minWidth: 0 }),
  workOrderDevice: style({ fontSize: 16, fontWeight: 600, color: '#1a1a1a', lineHeight: '22px' }),
  workOrderSubId: style({ fontSize: 12, color: '#888', lineHeight: '17px' }),
  signBtn: style({ backgroundColor: '#0161de', border: 'none', borderRadius: 8, color: '#ffffff', fontSize: 14, fontWeight: 600, paddingLeft: 16, paddingRight: 16, paddingTop: 8, paddingBottom: 8, cursor: 'pointer', fontFamily: 'inherit', flexShrink: 0 }),
};
