import { globalStyle, style } from '@vanilla-extract/css';
import { listItemInner } from '@filament/react/list-styles';

export const profileStyles = {
  // ── Page shell ────────────────────────────────────────────────────────────
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: '100%',
    overflowX: 'hidden',
    paddingBottom: 32,
    backgroundColor: '#F0F9FF',
  }),

  // ── Hero ──────────────────────────────────────────────────────────────────
  hero: style({
    backgroundColor: '#0161de',
    display: 'flex',
    flexDirection: 'column',
    color: '#ffffff',
    paddingBottom: 30,
  }),
  contentPanel: style({
    position: 'relative',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#F0F9FF',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    marginTop: -20,
    paddingTop: 4,
  }),
  heroTop: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: '4px 20px 16px',
  }),
  heroTextGroup: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  }),
  heroName: style({
    display: 'block',
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 700,
    lineHeight: '28px',
  }),
  heroUsernameBtn: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    background: 'none',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  heroSubtext: style({
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: 12,
  }),
  roleRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  }),
  roleTagAdmin: style({
    backgroundColor: '#dce8fd',
    color: '#0161de',
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 3,
    paddingBottom: 3,
    border: '1px solid #b3cef5',
  }),
  roleTagUser: style({
    backgroundColor: '#f0f4fb',
    color: '#3a5278',
    fontSize: 12,
    fontWeight: 500,
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 3,
    paddingBottom: 3,
    border: '1px solid #c5d5ec',
  }),
  deviceSummaryChip: style({
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 500,
    borderRadius: 100,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 2,
    paddingBottom: 2,
    border: '1px solid rgba(255, 255, 255, 0.25)',
  }),
  deviceSummaryChipBtn: style({
    background: 'none',
    border: 'none',
    padding: 0,
    margin: 0,
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  heroAccountRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: 44,
    minHeight: 44,
    padding: '0 20px',
    borderTop: 'none',
    borderLeft: 'none',
    borderRight: 'none',
    borderBottom: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  heroAccountLeft: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    fontSize: 13,
    color: '#ffffff',
  }),
  heroAccountRight: style({
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
  }),
  heroRoleAdmin: style({
    fontSize: 11,
    fontWeight: 600,
    color: '#ffffff',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 100,
    paddingLeft: 7,
    paddingRight: 7,
    paddingTop: 2,
    paddingBottom: 2,
    border: '1px solid rgba(255, 255, 255, 0.25)',
  }),
  heroRoleUser: style({
    fontSize: 11,
    fontWeight: 600,
    color: '#ffffff',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 100,
    paddingLeft: 7,
    paddingRight: 7,
    paddingTop: 2,
    paddingBottom: 2,
    border: '1px solid rgba(255, 255, 255, 0.25)',
  }),
  permissionTag: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#f0f4fb',
    color: '#3a5278',
    fontSize: 11,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 3,
    paddingBottom: 3,
    borderRadius: 100,
    border: '1px solid #c5d5ec',
  }),
  permissionDotSmall: style({
    width: 5,
    height: 5,
    borderRadius: '50%',
    backgroundColor: '#4ade80',
    flexShrink: 0,
  }),

  // ── Section Card wrapper ───────────────────────────────────────────────────
  sectionCard: style({
    margin: '16px 16px 0',
    width: 'calc(100% - 32px)',
  }),

  // ── Messages preview ──────────────────────────────────────────────────────
  sectionHeaderRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '12px 16px 8px',
    gap: 8,
  }),
  sectionLink: style({
    fontSize: 13,
    color: '#0161de',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    fontFamily: 'inherit',
  }),
  sectionSpacer: style({
    flex: 1,
  }),
  subscribeBtn: style({
    fontSize: 12,
    color: '#0161de',
    background: 'none',
    border: '1px solid #0161de',
    borderRadius: 10,
    cursor: 'pointer',
    padding: '2px 9px',
    fontFamily: 'inherit',
  }),
  msgRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    padding: '10px 16px',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    textAlign: 'left',
    width: '100%',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  }),
  msgRowBordered: style({
    borderTop: '1px solid #f0f0f0',
  }),
  msgUnreadDotSlot: style({
    width: 7,
    flexShrink: 0,
    paddingTop: 5,
  }),
  msgContent: style({
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
  }),
  msgRowTop: style({
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  }),
  msgUnreadDot: style({
    width: 7,
    height: 7,
    borderRadius: '50%',
    backgroundColor: '#0161de',
    flexShrink: 0,
  }),
  msgTitle: style({
    flex: 1,
    fontSize: 14,
    fontWeight: 500,
    color: '#1a2234',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  msgTime: style({
    fontSize: 12,
    color: '#aaa',
    flexShrink: 0,
    marginLeft: 4,
  }),
  msgBody: style({
    fontSize: 12,
    color: '#8898aa',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  msgEmpty: style({
    padding: '12px 16px 16px',
    textAlign: 'center',
    borderTop: '1px solid #f0f0f0',
  }),

  // ── Quick tools grid ──────────────────────────────────────────────────────
  cardSectionTitle: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#1a2234',
  }),
  toolSectionTitle: style({
    padding: '14px 16px 8px',
  }),
  toolGrid: style({
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: 10,
    padding: '4px 14px 20px',
  }),
  toolItem: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    padding: '8px 6px',
    backgroundColor: '#f0f4fb',
    borderRadius: 12,
    cursor: 'pointer',
    border: 'none',
    fontFamily: 'inherit',
  }),
  toolIconWrap: style({
    width: 38,
    height: 38,
    borderRadius: '50%',
    backgroundColor: '#dce8fd',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  toolLabel: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#1a2234',
    textAlign: 'center',
    lineHeight: '16px',
  }),
  toolSub: style({
    fontSize: 12,
    color: '#8898aa',
    textAlign: 'center',
    lineHeight: '14px',
  }),

  // ── Tool link rows (secondary tools) ─────────────────────────────────────
  toolLinks: style({
    borderTop: '1px solid #edf0f4',
    marginTop: 0,
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
  }),
  toolLinkRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    height: 48,
    padding: '0 10px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    width: '100%',
    boxSizing: 'border-box',
    textAlign: 'left',
    selectors: {
      '&:nth-child(1)': {
        borderRight: '1px solid #f0f2f5',
      },
    },
  }),
  toolLinkWide: style({
    gridColumn: '1 / -1',
    borderTop: '1px solid #f0f2f5',
  }),
  toolLinkLeft: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  }),
  toolLinkIconWrap: style({
    width: 30,
    height: 30,
    borderRadius: '50%',
    backgroundColor: '#dce8fd',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  }),
  toolLinkInfo: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    alignItems: 'flex-start',
    overflow: 'hidden',
  }),
  toolLinkLabel: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#1a2234',
    lineHeight: '16px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    width: '100%',
  }),
  toolLinkSub: style({
    fontSize: 12,
    color: '#8898aa',
    lineHeight: '14px',
  }),

  // ── Account & permission list (label left, value right) ───────────────────
  infoList: style({}),
  infoValueBold: style({
    fontWeight: 600,
    color: '#0161de',
  }),  accountHeader: style({
    fontSize: 11,
    color: '#8898aa',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    padding: '12px 16px 6px',
  }),
  accountRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderTop: '1px solid #f2f4f7',
    width: '100%',
    boxSizing: 'border-box',
  }),
  accountRowBtn: style({
    background: 'none',
    border: 'none',
    textAlign: 'left',
    fontFamily: 'inherit',
    cursor: 'pointer',
  }),
  accountLabel: style({
    fontSize: 14,
    color: '#1a2234',
  }),
  accountRight: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  }),
  accountValue: style({
    fontSize: 14,
    color: '#8898aa',
  }),
  upgradeInAccount: style({
    borderTop: '1px dashed #e4e8f0',
    padding: '14px 16px 16px',
  }),

  campusExpandWrap: style({
    borderTop: '1px dashed #e4e8f0',
    padding: '14px 16px 16px',
  }),

  // ── Upgrade section ───────────────────────────────────────────────────────
  upgradeContent: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  }),

  // state 2 (pending) badge
  upgradeStatusBadge: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#eff5ff',
    border: '1px solid #b3d4ff',
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 12,
    paddingTop: 4,
    paddingBottom: 4,
    alignSelf: 'flex-start',
  }),
  upgradeStatusDot: style({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: '#0161de',
    flexShrink: 0,
    animation: 'none',
  }),

  // state 4 (cooldown) badge
  upgradeStatusBadgeCooldown: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#fff8f0',
    border: '1px solid #ffd6a5',
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 12,
    paddingTop: 4,
    paddingBottom: 4,
    alignSelf: 'flex-start',
  }),
  upgradeStatusDotCooldown: style({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: '#f59e0b',
    flexShrink: 0,
  }),

  // meta row (submitted date / hospitals)
  upgradeMeta: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    backgroundColor: '#f8f9fb',
    borderRadius: 8,
    padding: '10px 12px',
  }),
  upgradeMetaRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
  }),
  upgradeMetaLabel: style({
    fontSize: 12,
    color: '#8898aa',
    flexShrink: 0,
    width: 56,
  }),
  upgradeMetaValue: style({
    fontSize: 12,
    color: '#444',
    lineHeight: '18px',
  }),

  upgradeNote: style({
    fontSize: 12,
    color: '#0161de',
    borderLeft: '3px solid #b3d4ff',
    paddingLeft: 8,
    marginTop: 2,
  }),

  // demo controls row
  demoRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 8,
    borderTop: '1px dashed #e0e0e0',
    marginTop: 4,
  }),
  demoLabel: style({
    fontSize: 11,
    color: '#aaa',
    marginRight: 2,
  }),
  demoBtnApprove: style({
    fontSize: 11,
    color: '#1a7f37',
    backgroundColor: '#e6f9ed',
    border: '1px solid #a8e6bc',
    borderRadius: 100,
    padding: '3px 10px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  demoBtnReject: style({
    fontSize: 11,
    color: '#d0021b',
    backgroundColor: '#fff0f0',
    border: '1px solid #ffb3b3',
    borderRadius: 100,
    padding: '3px 10px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),

  // ── Logout button ─────────────────────────────────────────────────────────
  logoutBtn: style({
    width: '100%',
    padding: '14px 16px',
    textAlign: 'left',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    display: 'block',
  }),
  // ── About section rows ────────────────────────────────────────────────────
  aboutRow: style({
    width: '100%',
    border: 'none',
    borderBottom: '1px solid #f0f2f5',
    background: 'none',
    padding: '14px 16px',
    fontFamily: 'inherit',
    fontSize: 14,
    color: '#1a2234',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    cursor: 'pointer',
    selectors: {
      '&:last-child': { borderBottom: 'none' },
    },
  }),

  // ── Modal overlay ─────────────────────────────────────────────────────────
  modalBackdrop: style({
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 200,
  }),
  modalCard: style({
    background: '#ffffff',
    borderRadius: 16,
    padding: '28px 24px 20px',
    width: 'min(320px, calc(100vw - 48px))',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
  }),
  modalTitle: style({
    fontSize: 17,
    fontWeight: 600,
    color: '#1a2234',
    textAlign: 'center',
  }),
  modalBody: style({
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    lineHeight: 1.6,
  }),
  modalConfirmBtn: style({
    marginTop: 8,
    width: '100%',
    padding: '12px 0',
    background: '#0161de',
    color: '#ffffff',
    border: 'none',
    borderRadius: 8,
    fontSize: 15,
    fontWeight: 500,
    fontFamily: 'inherit',
    cursor: 'pointer',
  }),
  modalPhoneLabel: style({
    fontSize: 13,
    color: '#9ca3af',
  }),
  modalPhoneNumber: style({
    fontSize: 26,
    fontWeight: 700,
    color: '#0161de',
    letterSpacing: 1,
  }),
  modalBtnRow: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    width: '100%',
    marginTop: 4,
  }),
  modalCallBtn: style({
    display: 'block',
    textAlign: 'center',
    padding: '12px 0',
    background: '#0161de',
    color: '#ffffff',
    border: 'none',
    borderRadius: 8,
    fontSize: 15,
    fontWeight: 500,
    fontFamily: 'inherit',
    cursor: 'pointer',
    textDecoration: 'none',
  }),
  modalCancelBtn: style({
    padding: '12px 0',
    background: 'none',
    color: '#6b7280',
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    fontSize: 15,
    fontFamily: 'inherit',
    cursor: 'pointer',
  }),
};

// Make info list items flex with label on left, value on right
globalStyle(`${profileStyles.infoList} ${listItemInner}`, {
  display: 'flex',
  width: '100%',
  justifyContent: 'space-between',
  alignItems: 'center',
});
