import { globalStyle, style } from '@vanilla-extract/css';
import { listItemInner } from '@filament/react/list-styles';

export const profileStyles = {
  // ── Page shell ────────────────────────────────────────────────────────────
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: '100%',
    overflowX: 'hidden',
    paddingBottom: 32,
    backgroundColor: '#f2f4f7',
  }),

  // ── Hero ──────────────────────────────────────────────────────────────────
  hero: style({
    backgroundColor: '#0161de',
    padding: '24px 20px',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    color: '#ffffff',
  }),
  heroTextGroup: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  }),
  heroName: style({
    display: 'block',
    color: '#ffffff',
  }),
  heroSubtext: style({
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
  }),
  roleRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  }),
  roleTagAdmin: style({
    backgroundColor: 'rgba(255,255,255,0.2)',
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 3,
    paddingBottom: 3,
    border: '1px solid rgba(255,255,255,0.4)',
  }),
  roleTagUser: style({
    backgroundColor: 'rgba(255,255,255,0.15)',
    color: 'rgba(255,255,255,0.9)',
    fontSize: 12,
    fontWeight: 500,
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 3,
    paddingBottom: 3,
    border: '1px solid rgba(255,255,255,0.3)',
  }),
  deviceSummaryChip: style({
    backgroundColor: 'rgba(255,255,255,0.1)',
    color: 'rgba(255,255,255,0.88)',
    fontSize: 11,
    fontWeight: 500,
    borderRadius: 100,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 2,
    paddingBottom: 2,
    border: '1px solid rgba(255,255,255,0.22)',
  }),
  deviceSummaryChipBtn: style({
    background: 'none',
    border: 'none',
    padding: 0,
    margin: 0,
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  permissionTag: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255,255,255,0.15)',
    color: 'rgba(255,255,255,0.85)',
    fontSize: 11,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 3,
    paddingBottom: 3,
    borderRadius: 100,
    border: '1px solid rgba(255,255,255,0.25)',
  }),
  permissionDotSmall: style({
    width: 5,
    height: 5,
    borderRadius: '50%',
    backgroundColor: '#4ade80',
    flexShrink: 0,
  }),

  // ── Section Card wrapper ───────────────────────────────────────────────────
  sectionCard: style({
    margin: '16px 16px 0',
    width: 'calc(100% - 32px)',
  }),

  // ── Messages preview ──────────────────────────────────────────────────────
  sectionHeaderRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '12px 16px 8px',
    gap: 8,
  }),
  sectionLink: style({
    fontSize: 13,
    color: '#0161de',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    marginLeft: 'auto',
    fontFamily: 'inherit',
  }),
  msgRow: style({
    display: 'flex',
    flexDirection: 'column',
    padding: '10px 16px',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    textAlign: 'left',
    width: '100%',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  }),
  msgRowBordered: style({
    borderTop: '1px solid #f0f0f0',
  }),
  msgRowTop: style({
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginBottom: 3,
  }),
  msgUnreadDot: style({
    width: 7,
    height: 7,
    borderRadius: '50%',
    backgroundColor: '#0161de',
    flexShrink: 0,
  }),
  msgTitle: style({
    flex: 1,
    fontSize: 13,
    fontWeight: 500,
    color: '#1a2234',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  msgTime: style({
    fontSize: 12,
    color: '#aaa',
    flexShrink: 0,
    marginLeft: 4,
  }),
  msgBody: style({
    fontSize: 12,
    color: '#8898aa',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
    paddingLeft: 13,
  }),
  msgEmpty: style({
    padding: '12px 16px 16px',
    textAlign: 'center',
    borderTop: '1px solid #f0f0f0',
  }),

  // ── Quick tools grid ──────────────────────────────────────────────────────
  cardSectionTitle: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#1a2234',
  }),
  toolSectionTitle: style({
    padding: '12px 16px 2px',
  }),
  toolGrid: style({
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 8,
    padding: '8px 16px 14px',
  }),
  toolItem: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: '10px 6px',
    backgroundColor: '#f0f4ff',
    borderRadius: 12,
    cursor: 'pointer',
    border: 'none',
    fontFamily: 'inherit',
  }),
  toolIconWrap: style({
    width: 36,
    height: 36,
    borderRadius: '50%',
    backgroundColor: '#e0eaff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  toolLabel: style({
    fontSize: 12,
    fontWeight: 600,
    color: '#1a2234',
    textAlign: 'center',
    lineHeight: '16px',
  }),
  toolSub: style({
    fontSize: 11,
    color: '#8898aa',
    textAlign: 'center',
    lineHeight: '14px',
  }),

  // ── Tool link rows (secondary tools) ─────────────────────────────────────
  toolLinks: style({
    borderTop: '1px solid #edf0f4',
    marginTop: 4,
    display: 'flex',
    flexDirection: 'column',
  }),
  toolLinkRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 16px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    width: '100%',
    boxSizing: 'border-box',
    selectors: {
      '& + &': {
        borderTop: '1px solid #f2f4f7',
      },
    },
  }),
  toolLinkLeft: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  }),
  toolLinkIconWrap: style({
    width: 30,
    height: 30,
    borderRadius: '50%',
    backgroundColor: '#eff3ff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  }),
  toolLinkInfo: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    alignItems: 'flex-start',
  }),
  toolLinkLabel: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#1a2234',
  }),
  toolLinkSub: style({
    fontSize: 11,
    color: '#8898aa',
  }),

  // ── Account & permission list (label left, value right) ───────────────────
  infoList: style({}),
  infoValueBold: style({
    fontWeight: 600,
    color: '#0161de',
  }),  accountHeader: style({
    fontSize: 11,
    color: '#8898aa',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    padding: '12px 16px 6px',
  }),
  accountRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderTop: '1px solid #f2f4f7',
    width: '100%',
    boxSizing: 'border-box',
  }),
  accountRowBtn: style({
    background: 'none',
    border: 'none',
    textAlign: 'left',
    fontFamily: 'inherit',
    cursor: 'pointer',
  }),
  accountLabel: style({
    fontSize: 14,
    color: '#1a2234',
  }),
  accountRight: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  }),
  accountValue: style({
    fontSize: 14,
    color: '#8898aa',
  }),
  upgradeInAccount: style({
    borderTop: '1px dashed #e4e8f0',
    padding: '14px 16px 16px',
  }),

  // ── Upgrade section ───────────────────────────────────────────────────────
  upgradeContent: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  }),

  // state 2 (pending) badge
  upgradeStatusBadge: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#eff5ff',
    border: '1px solid #b3d4ff',
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 12,
    paddingTop: 4,
    paddingBottom: 4,
    alignSelf: 'flex-start',
  }),
  upgradeStatusDot: style({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: '#0161de',
    flexShrink: 0,
    animation: 'none',
  }),

  // state 4 (cooldown) badge
  upgradeStatusBadgeCooldown: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#fff8f0',
    border: '1px solid #ffd6a5',
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 12,
    paddingTop: 4,
    paddingBottom: 4,
    alignSelf: 'flex-start',
  }),
  upgradeStatusDotCooldown: style({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: '#f59e0b',
    flexShrink: 0,
  }),

  // meta row (submitted date / hospitals)
  upgradeMeta: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    backgroundColor: '#f8f9fb',
    borderRadius: 8,
    padding: '10px 12px',
  }),
  upgradeMetaRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
  }),
  upgradeMetaLabel: style({
    fontSize: 12,
    color: '#8898aa',
    flexShrink: 0,
    width: 56,
  }),
  upgradeMetaValue: style({
    fontSize: 12,
    color: '#444',
    lineHeight: '18px',
  }),

  upgradeNote: style({
    fontSize: 12,
    color: '#0161de',
    borderLeft: '3px solid #b3d4ff',
    paddingLeft: 8,
    marginTop: 2,
  }),

  // demo controls row
  demoRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 8,
    borderTop: '1px dashed #e0e0e0',
    marginTop: 4,
  }),
  demoLabel: style({
    fontSize: 11,
    color: '#aaa',
    marginRight: 2,
  }),
  demoBtnApprove: style({
    fontSize: 11,
    color: '#1a7f37',
    backgroundColor: '#e6f9ed',
    border: '1px solid #a8e6bc',
    borderRadius: 100,
    padding: '3px 10px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  demoBtnReject: style({
    fontSize: 11,
    color: '#d0021b',
    backgroundColor: '#fff0f0',
    border: '1px solid #ffb3b3',
    borderRadius: 100,
    padding: '3px 10px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),

  // ── Logout button ─────────────────────────────────────────────────────────
  logoutBtn: style({
    width: '100%',
    padding: '14px 16px',
    textAlign: 'left',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    display: 'block',
  }),
  settingInlineBtn: style({
    width: '100%',
    border: 'none',
    background: 'none',
    padding: 0,
    margin: 0,
    fontFamily: 'inherit',
    fontSize: 14,
    color: '#1a2234',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    cursor: 'pointer',
  }),
};

// Make info list items flex with label on left, value on right
globalStyle(`${profileStyles.infoList} ${listItemInner}`, {
  display: 'flex',
  width: '100%',
  justifyContent: 'space-between',
  alignItems: 'center',
});
