import { style } from '@vanilla-extract/css';

export const profileStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: '100%',
    overflowX: 'hidden',
    paddingBottom: 24,
  }),
  hero: style({
    backgroundColor: '#0161de',
    padding: '28px 16px 24px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
  }),
  avatar: style({
    width: 64,
    height: 64,
    borderRadius: '50%',
    backgroundColor: 'rgba(255,255,255,0.25)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 24,
    fontWeight: 700,
    color: '#ffffff',
  }),
  name: style({
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 600,
    lineHeight: '26px',
    textAlign: 'center',
  }),
  roleRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  }),
  roleTagAdmin: style({
    backgroundColor: 'rgba(255,255,255,0.2)',
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 3,
    paddingBottom: 3,
    border: '1px solid rgba(255,255,255,0.4)',
  }),
  roleTagUser: style({
    backgroundColor: 'rgba(255,255,255,0.15)',
    color: 'rgba(255,255,255,0.9)',
    fontSize: 12,
    fontWeight: 500,
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 3,
    paddingBottom: 3,
    border: '1px solid rgba(255,255,255,0.3)',
  }),
  section: style({
    margin: '16px 16px 0',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
  }),
  sectionTitle: style({
    fontSize: 12,
    fontWeight: 600,
    color: '#888',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    padding: '12px 16px 4px',
  }),
  infoRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderBottom: '1px solid #f0f0f0',
  }),
  infoRowLast: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
  }),
  infoLabel: style({
    fontSize: 14,
    color: '#333',
    lineHeight: '20px',
  }),
  infoValue: style({
    fontSize: 14,
    color: '#666',
    lineHeight: '20px',
    textAlign: 'right',
  }),
  infoValueBold: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#0072db',
    lineHeight: '20px',
  }),
  permissionBadge: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    padding: '12px 16px',
    backgroundColor: '#f0f6ff',
    margin: '0 16px',
    marginTop: 16,
    borderRadius: 10,
  }),
  permissionDot: style({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: '#00b259',
    flexShrink: 0,
  }),
  permissionText: style({
    fontSize: 13,
    color: '#333',
    lineHeight: '18px',
    flex: 1,
  }),
  upgradeContent: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    padding: '16px',
  }),
  upgradeTitle: style({
    fontSize: 15,
    fontWeight: 600,
    color: '#222',
    lineHeight: '22px',
  }),
  upgradeBody: style({
    fontSize: 13,
    color: '#666',
    lineHeight: '20px',
  }),
  upgradeStatus: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#0072db',
    lineHeight: '20px',
  }),
  upgradeStatusPending: style({
    fontSize: 13,
    color: '#888',
    lineHeight: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  }),
  upgradeStatusApproved: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#00963a',
    lineHeight: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  }),
  upgradeSubmitDate: style({
    fontSize: 12,
    color: '#aaa',
    lineHeight: '18px',
  }),
  upgradeNote: style({
    fontSize: 12,
    color: '#0072db',
    lineHeight: '18px',
    borderLeft: '3px solid #b3d4ff',
    paddingLeft: 8,
  }),
  // 消息中心 entry row
  messagesEntryRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '14px 16px',
    cursor: 'pointer',
  }),
  messagesEntryLabel: style({
    fontSize: 15,
    color: '#333',
    lineHeight: '22px',
    flex: 1,
  }),
  unreadBadge: style({
    backgroundColor: '#e02020',
    color: '#ffffff',
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 100,
    minWidth: 18,
    height: 18,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 5,
    paddingRight: 5,
    marginRight: 8,
  }),
  settingsRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 16px',
    borderBottom: '1px solid #f0f0f0',
    cursor: 'pointer',
  }),
  settingsRowLast: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 16px',
    cursor: 'pointer',
  }),
  settingsLabel: style({
    fontSize: 15,
    color: '#333',
    lineHeight: '22px',
  }),
  settingsLabelDanger: style({
    fontSize: 15,
    color: '#e02020',
    lineHeight: '22px',
  }),
  chevron: style({
    fontSize: 14,
    color: '#bbb',
  }),
};
