import { keyframes, style } from '@vanilla-extract/css';

const scanMove = keyframes({
  '0%': { top: 0 },
  '50%': { top: 'calc(100% - 2px)' },
  '100%': { top: 0 },
});

export const scanCameraStyles = {
  page: style({
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 375,
    maxWidth: '100vw',
    backgroundColor: '#000',
    display: 'flex',
    flexDirection: 'column',
    zIndex: 200,
  }),
  header: style({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 20px',
    gap: 12,
    zIndex: 3,
    flexShrink: 0,
  }),
  closeBtn: style({
    width: 36,
    height: 36,
    borderRadius: '50%',
    backgroundColor: 'rgba(255,255,255,0.18)',
    border: 'none',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    flexShrink: 0,
  }),
  title: style({
    color: '#fff',
    fontSize: 16,
    fontWeight: 600,
    flex: 1,
    textAlign: 'center',
  }),
  modeToggle: style({
    display: 'flex',
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.15)',
    overflow: 'hidden',
    flexShrink: 0,
  }),
  modeBtn: style({
    padding: '5px 12px',
    fontSize: 13,
    color: 'rgba(255,255,255,0.65)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
  }),
  modeBtnActive: style({
    padding: '5px 12px',
    fontSize: 13,
    color: '#fff',
    backgroundColor: '#0161de',
    border: 'none',
    cursor: 'pointer',
    borderRadius: 20,
  }),
  viewfinderWrap: style({
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  video: style({
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    zIndex: 1,
  }),
  frame: style({
    position: 'relative',
    width: 240,
    height: 240,
    boxShadow: '0 0 0 9999px rgba(0,0,0,0.65)',
    borderRadius: 4,
    zIndex: 2,
    overflow: 'hidden',
  }),
  cornerTL: style({
    position: 'absolute',
    top: 0,
    left: 0,
    width: 28,
    height: 28,
    borderTop: '3px solid #fff',
    borderLeft: '3px solid #fff',
    borderTopLeftRadius: 2,
  }),
  cornerTR: style({
    position: 'absolute',
    top: 0,
    right: 0,
    width: 28,
    height: 28,
    borderTop: '3px solid #fff',
    borderRight: '3px solid #fff',
    borderTopRightRadius: 2,
  }),
  cornerBL: style({
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: 28,
    height: 28,
    borderBottom: '3px solid #fff',
    borderLeft: '3px solid #fff',
    borderBottomLeftRadius: 2,
  }),
  cornerBR: style({
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderBottom: '3px solid #fff',
    borderRight: '3px solid #fff',
    borderBottomRightRadius: 2,
  }),
  scanLine: style({
    position: 'absolute',
    left: 0,
    right: 0,
    height: 2,
    background: 'linear-gradient(90deg, transparent, #0161de, #0161de, transparent)',
    animationName: scanMove,
    animationDuration: '2s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
  }),
  noCamera: style({
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1a1a1a',
    zIndex: 1,
  }),
  noCameraText: style({
    color: 'rgba(255,255,255,0.5)',
    fontSize: 13,
    textAlign: 'center',
    padding: '0 24px',
    lineHeight: '20px',
  }),
  hint: style({
    color: 'rgba(255,255,255,0.6)',
    fontSize: 13,
    textAlign: 'center',
    padding: '24px 16px 8px',
    flexShrink: 0,
  }),
  bottomActions: style({
    padding: '8px 32px 52px',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    alignItems: 'center',
    flexShrink: 0,
  }),
  inputFallbackBtn: style({
    color: 'rgba(255,255,255,0.5)',
    fontSize: 13,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    textDecoration: 'underline',
    padding: 8,
  }),
};
