import { style } from '@vanilla-extract/css';

export const scanDeviceInputStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: '#f5f7fa',
  }),
  header: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: '14px 16px',
    backgroundColor: '#0161de',
  }),
  backBtn: style({
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 4,
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
  }),
  headerTitle: style({
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 600,
  }),
  content: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    padding: '24px 16px',
    gap: 16,
  }),
  desc: style({
    fontSize: 14,
    color: '#667',
    lineHeight: 1.6,
  }),
  inputCard: style({
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    border: '1px solid #e8ebf0',
  }),
  inputLabel: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#444',
  }),
  inputField: style({
    border: '1px solid #d0d7e2',
    borderRadius: 8,
    padding: '10px 12px',
    fontSize: 15,
    color: '#1a2234',
    outline: 'none',
    fontFamily: 'inherit',
    width: '100%',
    boxSizing: 'border-box',
  }),
  inputHint: style({
    fontSize: 12,
    color: '#aaa',
    lineHeight: 1.5,
  }),
  actionRow: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  }),
  btnPrimary: style({
    backgroundColor: '#0161de',
    color: '#ffffff',
    border: 'none',
    borderRadius: 10,
    padding: '13px 0',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    width: '100%',
  }),
  btnPrimaryDisabled: style({
    backgroundColor: '#c0c8d8',
    color: '#ffffff',
    border: 'none',
    borderRadius: 10,
    padding: '13px 0',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'not-allowed',
    fontFamily: 'inherit',
    width: '100%',
  }),
  dividerRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  }),
  dividerLine: style({
    flex: 1,
    height: 1,
    backgroundColor: '#e0e4ea',
  }),
  dividerText: style({
    fontSize: 12,
    color: '#aaa',
    flexShrink: 0,
  }),
  btnOutline: style({
    backgroundColor: 'transparent',
    color: '#0161de',
    border: '1px solid #0161de',
    borderRadius: 10,
    padding: '12px 0',
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
    fontFamily: 'inherit',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  }),
};
