import { globalStyle, style } from '@vanilla-extract/css';

export const scanDeviceInputStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: '#f5f7fa',
  }),
  header: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: '14px 16px',
    backgroundColor: '#0161de',
  }),
  backBtn: style({
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 4,
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
  }),
  headerTitle: style({
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 600,
  }),
  content: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    padding: '24px 16px',
    gap: 16,
  }),
  desc: style({
    fontSize: 14,
    color: '#667',
    lineHeight: 1.6,
  }),
  inputCard: style({
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    border: '1px solid #e8ebf0',
  }),
  inputLabel: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#444',
  }),
  inputField: style({
    border: '1px solid #d0d7e2',
    borderRadius: 8,
    padding: '10px 12px',
    fontSize: 15,
    color: '#1a2234',
    outline: 'none',
    fontFamily: 'inherit',
    width: '100%',
    boxSizing: 'border-box',
  }),
  inputHint: style({
    fontSize: 12,
    color: '#aaa',
    lineHeight: 1.5,
  }),
  historySection: style({
    display: 'flex',
    flexDirection: 'column',
    paddingTop: 8,
  }),
  historyHeader: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 4,
    marginBottom: 2,
  }),
  historyTitle: style({
    fontSize: 12,
    color: '#aab0bc',
    fontWeight: 500,
  }),
  historyClear: style({
    background: 'none',
    border: 'none',
    fontSize: 12,
    color: '#aab0bc',
    cursor: 'pointer',
    fontFamily: 'inherit',
    padding: 0,
  }),
  historyItem: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: '10px 0',
    background: 'none',
    border: 'none',
    borderTop: '1px solid #f2f4f7',
    cursor: 'pointer',
    fontFamily: 'inherit',
    width: '100%',
    boxSizing: 'border-box',
    textAlign: 'left',
  }),
  historyItemText: style({
    flex: 1,
    fontSize: 14,
    color: '#1a2234',
  }),
  actionRow: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  }),
  btnPrimary: style({
    backgroundColor: '#0161de',
    color: '#ffffff',
    border: 'none',
    borderRadius: 10,
    padding: '13px 0',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    width: '100%',
  }),
  btnPrimaryDisabled: style({
    backgroundColor: '#c0c8d8',
    color: '#ffffff',
    border: 'none',
    borderRadius: 10,
    padding: '13px 0',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'not-allowed',
    fontFamily: 'inherit',
    width: '100%',
  }),
  dividerRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  }),
  dividerLine: style({
    flex: 1,
    height: 1,
    backgroundColor: '#e0e4ea',
  }),
  dividerText: style({
    fontSize: 12,
    color: '#aaa',
    flexShrink: 0,
  }),
  btnOutline: style({
    backgroundColor: 'transparent',
    color: '#0161de',
    border: '1px solid #0161de',
    borderRadius: 10,
    padding: '12px 0',
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
    fontFamily: 'inherit',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  }),

  // ── Confirm view ────────────────────────────────────────────────────────────
  confirmContent: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '24px 16px',
    gap: 16,
    overflowY: 'auto',
  }),
  pictogramWrap: style({
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  }),
  deviceCard: style({
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    boxShadow: '0 2px 4px -2px rgba(0,0,0,0.1)',
  }),
  deviceCardTop: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  }),
  deviceNameRow: style({
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  }),
  contractBadge: style({
    display: 'none',
  }),
  deviceName: style({
    fontSize: 16,
    fontWeight: 600,
    color: '#00126e',
  }),
  deviceCampus: style({
    fontSize: 13,
    color: '#4a5565',
  }),
  deviceCardDivider: style({
    height: 1,
    backgroundColor: '#e5e7eb',
    margin: '4px 0',
  }),
  deviceMetaRow: style({
    display: 'flex',
    gap: 10,
  }),
  deviceMetaItem: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    flex: 1,
  }),
  deviceMetaLabel: style({
    fontSize: 11,
    color: '#6a7282',
  }),
  deviceMetaValue: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#00126e',
  }),
  actionButtons: style({
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    paddingTop: 4,
  }),
  bindSuccessBlock: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
  }),
  bindSuccessBadge: style({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: '10px 16px',
    fontSize: 14,
    color: '#16a34a',
    fontWeight: 500,
    border: '1.5px solid #bbf7d0',
    borderRadius: 10,
    backgroundColor: '#f0fdf4',
    width: '100%',
  }),
  bindNextBtn: style({
    background: 'none',
    border: 'none',
    color: '#0161de',
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
    padding: '4px 0',
  }),
  actionHint: style({
    fontSize: 12,
    color: '#9ca3af',
    textAlign: 'center',
    margin: 0,
  }),
  ultraBanner: style({
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: '13px 16px',
    background: '#f2f5fb',
    border: 'none',
    borderRadius: 10,
    cursor: 'pointer',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    textAlign: 'left',
  }),
  ultraBannerIcon: style({
    width: 40,
    height: 40,
    borderRadius: '50%',
    backgroundColor: '#0161de',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  }),
  ultraBannerInfo: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 3,
  }),
  ultraBannerTitle: style({
    fontSize: 15,
    fontWeight: 600,
    color: '#1a2234',
  }),
  ultraBannerSub: style({
    fontSize: 12,
    color: '#8898aa',
  }),
  ultraBannerChevron: style({
    flexShrink: 0,
  }),
  notFound: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
    padding: '8px 0',
    width: '100%',
  }),
  notFoundTitle: style({
    fontSize: 16,
    fontWeight: 600,
    color: '#1a2234',
    margin: 0,
  }),
  notFoundDesc: style({
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    lineHeight: 1.6,
    margin: 0,
  }),
};

globalStyle(`${scanDeviceInputStyles.pictogramWrap} svg`, {
  width: 192,
  height: 192,
});
