import { style } from '@vanilla-extract/css';

export const sparePartsAuthStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: '#ffffff',
  }),
  header: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: '10px 16px',
    backgroundColor: '#0161de',
    boxShadow: '0 2px 6px rgba(1,57,130,0.22)',
  }),
  backBtn: style({
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 4,
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
  }),
  headerTitle: style({
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 600,
  }),
  content: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 24px',
    gap: 16,
  }),
  icon: style({
    width: 80,
    height: 80,
    borderRadius: '50%',
    backgroundColor: '#e8f0fd',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  title: style({
    fontSize: 18,
    fontWeight: 700,
    color: '#1a2234',
    textAlign: 'center',
  }),
  desc: style({
    fontSize: 14,
    color: '#667',
    textAlign: 'center',
    lineHeight: 1.6,
  }),
  statusCard: style({
    width: '100%',
    marginTop: 16,
    padding: '16px 14px',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    border: '1px solid #e8ebf0',
  }),
  statusLabel: style({
    fontSize: 12,
    color: '#8898aa',
    fontWeight: 500,
    marginBottom: 8,
  }),
  statusValue: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#0161de',
  }),

  // ── Result screen ──────────────────────────────────────
  resultPage: style({
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: '#ffffff',
  }),
  resultHeader: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '0 16px',
    height: 48,
    backgroundColor: '#ffffff',
    borderBottom: '1px solid #eaecf0',
    flexShrink: 0,
  }),
  resultBackBtn: style({
    width: 44,
    height: 44,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    flexShrink: 0,
  }),
  resultHeaderTitle: style({
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: 600,
    color: 'rgba(0, 0, 0, 0.9)',
  }),
  resultCloseBtn: style({
    width: 44,
    height: 44,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    flexShrink: 0,
  }),
  resultContent: style({
    flex: 1,
    overflowY: 'auto',
    paddingLeft: 32,
    paddingRight: 32,
    paddingBottom: 40,
    display: 'flex',
    flexDirection: 'column',
  }),
  resultIconRow: style({
    paddingTop: 32,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#0161de',
  }),
  resultTitleBlock: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    marginTop: 16,
    alignItems: 'center',
  }),
  resultInfoTitle: style({
    fontSize: 28,
    fontWeight: 700,
    lineHeight: '32px',
    color: '#000000',
    textAlign: 'center',
  }),
  resultSerialNum: style({
    fontSize: 20,
    fontWeight: 400,
    lineHeight: '24px',
    color: '#000000',
    textAlign: 'center',
  }),
  resultDividerLine: style({
    height: 1,
    backgroundColor: '#e8eaed',
    width: '100%',
    marginTop: 16,
  }),
  resultDetails: style({
    paddingTop: 24,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  }),
  resultDetailRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 16,
    alignItems: 'flex-start',
  }),
  resultDetailLabel: style({
    fontSize: 20,
    fontWeight: 700,
    lineHeight: '24px',
    color: '#000000',
    flexShrink: 0,
    minWidth: 100,
  }),
  resultDetailValue: style({
    fontSize: 20,
    fontWeight: 400,
    lineHeight: '24px',
    color: '#000000',
  }),
  resultReferralCard: style({
    marginTop: 32,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: '14px 16px',
    borderRadius: 12,
    border: '1px solid #e0e9fb',
    backgroundColor: '#f5f8ff',
  }),
  resultReferralIcon: style({
    width: 40,
    height: 40,
    borderRadius: 10,
    overflow: 'hidden',
    flexShrink: 0,
  }),
  resultReferralBody: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
  }),
  resultReferralTitle: style({
    fontSize: 13,
    fontWeight: 700,
    color: '#0a1628',
    lineHeight: '18px',
  }),
  resultReferralSub: style({
    fontSize: 11,
    color: '#0161de',
    lineHeight: '16px',
  }),
  resultReferralBtn: style({
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    fontSize: 13,
    fontWeight: 600,
    color: '#0161de',
  }),

  // ── Guide screen ───────────────────────────────────────
  scrollContent: style({
    flex: 1,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
  }),
  illustrationWrap: style({
    width: '100%',
    background: 'linear-gradient(180deg, #ccdeff 0%, #e4eeff 55%, #f5f8ff 100%)',
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    overflow: 'hidden',
    paddingTop: 20,
  }),
  illustration: style({
    width: '100%',
    maxHeight: 240,
    objectFit: 'contain',
    objectPosition: 'bottom center',
    display: 'block',
  }),
  titleSection: style({
    flexShrink: 0,
    padding: '28px 24px 52px',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
  }),
  brandLabel: style({
    fontSize: 15,
    fontWeight: 700,
    color: '#0161de',
    letterSpacing: 0.4,
  }),
  mainTitle: style({
    fontSize: 22,
    fontWeight: 700,
    color: '#0a1628',
    lineHeight: '30px',
    marginBottom: 2,
  }),
  actionDesc: style({
    fontSize: 15,
    color: '#3a4256',
    lineHeight: '24px',
  }),
  highlight: style({
    fontWeight: 700,
    color: '#0a1628',
    background: 'linear-gradient(transparent 65%, rgba(1, 97, 222, 0.2) 65%)',
    borderRadius: 2,
    paddingLeft: 2,
    paddingRight: 2,
  }),
  metaNote: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    fontSize: 12,
    color: '#8898aa',
    lineHeight: '18px',
    paddingTop: 2,
  }),
  footer: style({
    padding: '16px 24px 28px',
    backgroundColor: '#ffffff',
    borderTop: '1px solid #eaecf0',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
  }),
  scanBtn: style({
    marginTop: 36,
    width: '100%',
    backgroundColor: '#0161de',
    color: '#ffffff',
    border: 'none',
    borderRadius: 12,
    padding: '15px 0',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    boxShadow: '0 4px 20px rgba(1, 97, 222, 0.35)',
  }),
};
