import { style } from '@vanilla-extract/css';

export const suServiceStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
  }),
  topBar: style({
    width: '100%',
    backgroundColor: '#0161de',
    padding: '12px 16px 16px',
    flexShrink: 0,
  }),
  topBarTitle: style({
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 600,
    lineHeight: '26px',
  }),
  topBarSub: style({
    color: 'rgba(255,255,255,0.75)',
    fontSize: 13,
    lineHeight: '20px',
    marginTop: 2,
  }),
  body: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    minHeight: 0,
  }),
  scanRow: style({
    padding: '12px 16px 0',
  }),
  searchRow: style({
    padding: '10px 16px 0',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  }),
  searchInput: style({
    flex: 1,
    minWidth: 0,
    height: 36,
    border: '1px solid #d0d7e0',
    borderRadius: 8,
    paddingLeft: 12,
    paddingRight: 12,
    fontSize: 14,
    color: '#1a1a1a',
    backgroundColor: '#f5f6f8',
    fontFamily: 'inherit',
    outline: 'none',
    boxSizing: 'border-box',
    ':focus': {
      borderColor: '#0072db',
      backgroundColor: '#ffffff',
    },
  }),
  filterToggleBtn: style({
    flexShrink: 0,
    height: 36,
    paddingLeft: 12,
    paddingRight: 12,
    border: '1px solid #d0d7e0',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    fontSize: 13,
    fontWeight: 500,
    color: '#555',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  }),
  filterToggleBtnActive: style({
    borderColor: '#0072db',
    color: '#0072db',
    backgroundColor: '#eef5ff',
  }),
  filterOverlay: style({
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 100,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
  }),
  filterBackdrop: style({
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0,0,0,0.45)',
  }),
  filterSheet: style({
    position: 'relative',
    backgroundColor: '#ffffff',
    borderRadius: '16px 16px 0 0',
    paddingBottom: 32,
  }),
  filterSheetHandle: style({
    width: 36,
    height: 4,
    backgroundColor: '#ddd',
    borderRadius: 2,
    marginTop: 10,
    marginLeft: 'auto',
    marginRight: 'auto',
  }),
  filterSheetHeader: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 12,
    paddingBottom: 8,
  }),
  filterSheetResetBtn: style({
    fontSize: 14,
    color: '#0072db',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    width: 40,
    textAlign: 'left',
  }),
  filterSheetTitle: style({
    fontSize: 16,
    fontWeight: 600,
    color: '#1a1a1a',
  }),
  filterSheetDoneBtn: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#0072db',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    width: 40,
    textAlign: 'right',
  }),
  filterSheetBody: style({
    paddingLeft: 16,
    paddingRight: 16,
  }),
  filterSheetGroupTitle: style({
    fontSize: 11,
    fontWeight: 600,
    color: '#999',
    marginTop: 14,
    marginBottom: 10,
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
  }),
  filterSheetChips: style({
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  }),
  filterSheetChip: style({
    borderRadius: 100,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 7,
    paddingBottom: 7,
    fontSize: 13,
    fontWeight: 500,
    border: '1.5px solid #e0e4ea',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    backgroundColor: '#ffffff',
    color: '#444',
  }),
  filterSheetChipActive: style({
    backgroundColor: '#0072db',
    borderColor: '#0072db',
    color: '#ffffff',
  }),
  filterSheetFooter: style({
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  }),
  filterSheetApplyBtn: style({
    width: '100%',
    height: 44,
    backgroundColor: '#0072db',
    color: '#ffffff',
    border: 'none',
    borderRadius: 8,
    fontSize: 15,
    fontWeight: 600,
    cursor: 'pointer',
  }),
  scanBanner: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#eef5ff',
    borderRadius: 10,
    padding: '10px 14px',
    gap: 8,
  }),
  scanBannerText: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    flex: 1,
  }),
  scanBannerTitle: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#00126e',
    lineHeight: '20px',
  }),
  scanBannerSub: style({
    fontSize: 12,
    color: '#666',
    lineHeight: '18px',
  }),
  scanBtn: style({
    backgroundColor: '#0072db',
    color: '#ffffff',
    border: 'none',
    borderRadius: 6,
    padding: '6px 14px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  }),
  filterRow: style({
    overflowX: 'auto',
    padding: '10px 0 4px',
    scrollbarWidth: 'none',
    '::-webkit-scrollbar': {
      display: 'none',
    },
  }),
  chipGroup: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    paddingLeft: 16,
    paddingRight: 16,
    width: 'max-content',
  }),
  chip: style({
    borderRadius: 100,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 5,
    paddingBottom: 5,
    fontSize: 13,
    fontWeight: 500,
    border: '1px solid #d0d7e0',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    backgroundColor: '#ffffff',
    color: '#333',
  }),
  chipActive: style({
    backgroundColor: '#0072db',
    borderColor: '#0072db',
    color: '#ffffff',
  }),
  listScrollArea: style({
    flex: 1,
    overflowY: 'auto',
    scrollbarWidth: 'none',
    '::-webkit-scrollbar': { display: 'none' },
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
  }),
  listHeader: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 10,
    paddingBottom: 4,
  }),
  emptyState: style({
    padding: '32px 0',
    textAlign: 'center',
  }),
  loadMoreWrap: style({
    paddingTop: 8,
    paddingBottom: 20,
    display: 'flex',
    justifyContent: 'center',
  }),
  loadMoreBtn: style({
    background: 'none',
    border: '1px solid #d0d0d0',
    borderRadius: 100,
    color: '#0161de',
    fontSize: 13,
    fontWeight: 500,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 8,
    paddingBottom: 8,
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
};
