import { style } from '@vanilla-extract/css';

export const suServiceStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: '100%',
    overflowX: 'hidden',
  }),
  topBar: style({
    width: '100%',
    backgroundColor: '#0161de',
    padding: '12px 16px 16px',
    flexShrink: 0,
  }),
  topBarTitle: style({
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 600,
    lineHeight: '26px',
  }),
  topBarSub: style({
    color: 'rgba(255,255,255,0.75)',
    fontSize: 13,
    lineHeight: '20px',
    marginTop: 2,
  }),
  body: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  }),
  scanRow: style({
    padding: '12px 16px 0',
  }),
  scanBanner: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#eef5ff',
    borderRadius: 10,
    padding: '10px 14px',
    gap: 8,
  }),
  scanBannerText: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    flex: 1,
  }),
  scanBannerTitle: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#00126e',
    lineHeight: '20px',
  }),
  scanBannerSub: style({
    fontSize: 12,
    color: '#666',
    lineHeight: '18px',
  }),
  scanBtn: style({
    backgroundColor: '#0072db',
    color: '#ffffff',
    border: 'none',
    borderRadius: 6,
    padding: '6px 14px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  }),
  filterRow: style({
    overflowX: 'auto',
    padding: '10px 0 4px',
    scrollbarWidth: 'none',
    '::-webkit-scrollbar': {
      display: 'none',
    },
  }),
  chipGroup: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    paddingLeft: 16,
    paddingRight: 16,
    width: 'max-content',
  }),
  chip: style({
    borderRadius: 100,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 5,
    paddingBottom: 5,
    fontSize: 13,
    fontWeight: 500,
    border: '1px solid #d0d7e0',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    backgroundColor: '#ffffff',
    color: '#333',
  }),
  chipActive: style({
    backgroundColor: '#0072db',
    borderColor: '#0072db',
    color: '#ffffff',
  }),
  listSection: style({
    padding: '10px 0 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  }),
  listHeader: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 16,
    paddingBottom: 4,
  }),
  emptyState: style({
    padding: '32px 0',
    textAlign: 'center',
  }),
};
