import { style } from '@vanilla-extract/css';
import { BOTTOM_BAR_HEIGHT } from '../components/shared-bottom-bar.css';

export const userDeviceStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: '100%',
    overflowX: 'hidden',
    backgroundColor: '#F0F9FF',
  }),
  topBar: style({
    backgroundColor: '#0161de',
    padding: '12px 16px 16px',
    flexShrink: 0,
  }),
  topBarTitle: style({
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 600,
    lineHeight: '26px',
  }),
  topBarHeaderRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  }),
  scanBtnTop: style({
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 32,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 16,
    border: 'none',
    backgroundColor: '#ffffff',
    color: '#0161de',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
  }),
  topBarSub: style({
    color: 'rgba(255,255,255,0.75)',
    fontSize: 13,
    lineHeight: '20px',
    marginTop: 2,
  }),
  statsScrollRow: style({
    overflowX: 'auto',
    marginTop: 14,
    marginLeft: -16,
    marginRight: -16,
    paddingLeft: 16,
    scrollbarWidth: 'none',
  }),
  statsRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    paddingRight: 16,
    width: 'max-content',
  }),
  statCard: style({
    minWidth: 80,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 10,
    padding: '8px 10px',
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    cursor: 'pointer',
    border: 'none',
    fontFamily: 'inherit',
    textAlign: 'left',
    color: 'rgba(255,255,255,0.9)',
  }),
  statCardActive: style({
    backgroundColor: 'rgba(255,255,255,0.95)',
    color: '#0161de',
  }),
  statNumber: style({
    color: 'inherit',
    fontSize: 22,
    fontWeight: 700,
    lineHeight: '28px',
  }),
  statLabel: style({
    color: 'inherit',
    fontSize: 11,
    lineHeight: '16px',
    opacity: 0.8,
  }),
  searchFilterRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    padding: '12px 16px',
    alignItems: 'center',
    backgroundColor: 'transparent',
    flexShrink: 0,
  }),
  searchBox: style({
    width: 96,
    flexShrink: 0,
  }),
  antiCounterfeitSectionBanner: style({
    margin: '12px 16px 8px',
    padding: '12px 14px',
    borderRadius: 12,
    backgroundColor: '#f0f7ff',
    border: '1px solid #d0e8ff',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    width: 'calc(100% - 32px)',
    fontFamily: 'inherit',
    textAlign: 'left',
  }),
  antiCounterfeitBannerIcon: style({
    flexShrink: 0,
    width: 32,
    height: 32,
    borderRadius: '50%',
    backgroundColor: '#0161de',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  antiCounterfeitBannerContent: style({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  }),
  antiCounterfeitBannerTitle: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#0161de',
  }),
  antiCounterfeitBannerDesc: style({
    fontSize: 11,
    color: '#667',
  }),
  listSection: style({
    padding: '12px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  }),
  listSectionManaging: style({
    paddingBottom: 76,
  }),
  sectionHeader: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingBottom: 4,
  }),
  groupHeader: style({
    display: 'flex',
    alignItems: 'baseline',
    gap: 6,
    width: '100%',
    marginTop: 6,
    marginBottom: 2,
    padding: '4px 2px',
  }),
  manageHeaderActions: style({
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  }),
  sectionHeaderLeft: style({
    display: 'flex',
    alignItems: 'flex-end',
    gap: 10,
    minWidth: 0,
  }),
  headerDivider: style({
    alignSelf: 'flex-end',
    width: 1,
    height: 13,
    marginBottom: 4,
    backgroundColor: '#dbe3ee',
    flexShrink: 0,
  }),
  manageEntryBtn: style({
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    background: 'none',
    border: 'none',
    color: '#0161de',
    fontSize: 13,
    fontWeight: 500,
    height: 20,
    lineHeight: '20px',
    fontFamily: 'inherit',
    cursor: 'pointer',
    padding: 0,
    whiteSpace: 'nowrap',
  }),
  recentUnboundEntry: style({
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
    background: 'none',
    border: 'none',
    padding: 0,
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 500,
    height: 20,
    lineHeight: '20px',
    color: '#0161de',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  }),
  recentUnboundCount: style({
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 17,
    height: 17,
    padding: '0 5px',
    borderRadius: 9,
    backgroundColor: '#e5f0ff',
    fontSize: 11,
    fontWeight: 600,
    lineHeight: 1,
  }),
  manageSelectAllBtn: style({
    flexShrink: 0,
    background: 'none',
    border: 'none',
    padding: 0,
    fontSize: 13,
    fontWeight: 500,
    color: '#0161de',
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  manageActionBarBtns: style({
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginLeft: 'auto',
  }),
  manageActionBar: style({
    position: 'fixed',
    bottom: BOTTOM_BAR_HEIGHT,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 375,
    maxWidth: '100vw',
    zIndex: 30,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 16px',
    backgroundColor: '#ffffff',
    borderTop: '1px solid #e3ecf6',
    boxShadow: '0 -2px 8px rgba(15, 42, 82, 0.06)',
  }),
  manageActionBarLabel: style({
    fontSize: 13,
    color: '#5b6779',
    whiteSpace: 'nowrap',
  }),
  groupHeaderLabel: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#15305c',
    flexShrink: 0,
  }),
  groupHeaderCount: style({
    flexShrink: 0,
    fontSize: 12,
    fontWeight: 500,
    color: '#8a94a6',
  }),
  emptyState: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 20,
    padding: '24px 0 40px',
    textAlign: 'center',
  }),
  emptyTitle: style({
    fontSize: 15,
    fontWeight: 600,
    lineHeight: '22px',
    color: '#15305c',
  }),

  emptyCopy: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 4,
  }),

  migrationBanner: style({
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 12px',
    borderRadius: 10,
    backgroundColor: '#eaf3ff',
    fontSize: 12.5,
    lineHeight: '18px',
    color: '#15305c',
  }),

  migrationBannerDone: style({
    backgroundColor: '#e8f6ee',
  }),

  migrationBannerClose: style({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 'auto',
    flexShrink: 0,
    background: 'none',
    border: 'none',
    padding: 0,
    color: '#5b6779',
    cursor: 'pointer',
  }),

  emptyHint: style({
    fontSize: 13,
    lineHeight: '20px',
    color: '#8a94a6',
  }),
  emptyActions: style({
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: 10,
    width: '100%',
    maxWidth: 280,
  }),
  emptyAction: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 4,
    padding: '14px 8px',
    borderRadius: 12,
    border: '1px solid #dce7f5',
    backgroundColor: '#ffffff',
    fontFamily: 'inherit',
    color: '#0161de',
    cursor: 'pointer',
  }),
  emptyActionIcon: style({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#eaf3ff',
  }),
  emptyActionLabel: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#15305c',
  }),
  emptyActionSub: style({
    fontSize: 11,
    color: '#8a94a6',
  }),
  emptyRecentLink: style({
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    background: 'none',
    border: 'none',
    padding: '2px 0',
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 500,
    color: '#0161de',
    cursor: 'pointer',
  }),
  campusSelectorRow: style({
    position: 'relative',
    marginTop: 8,
  }),
  campusSelectorBtn: style({
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    background: 'rgba(255,255,255,0.18)',
    border: '1px solid rgba(255,255,255,0.35)',
    borderRadius: 8,
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 500,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 5,
    paddingBottom: 5,
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  campusSelectorSingle: style({
    display: 'inline-block',
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 500,
  }),
  campusChevron: style({
    fontSize: 10,
    opacity: 0.8,
  }),
  campusBackdrop: style({
    position: 'fixed',
    inset: 0,
    zIndex: 40,
  }),
  campusDropdown: style({
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: 0,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    overflow: 'hidden',
    zIndex: 50,
    minWidth: 160,
    maxWidth: 280,
  }),
  campusDropdownItem: style({
    display: 'block',
    width: '100%',
    padding: '11px 14px',
    background: 'none',
    border: 'none',
    fontSize: 14,
    color: '#333',
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
  }),
  campusDropdownItemActive: style({
    backgroundColor: '#e8f2ff',
    color: '#0161de',
    fontWeight: 600,
  }),
  loadMoreWrap: style({
    paddingTop: 8,
    paddingBottom: 8,
    display: 'flex',
    justifyContent: 'center',
  }),
  loadMoreBtn: style({
    background: 'none',
    border: '1px solid #d0d0d0',
    borderRadius: 100,
    color: '#0161de',
    fontSize: 13,
    fontWeight: 500,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 8,
    paddingBottom: 8,
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
};
