import { style } from '@vanilla-extract/css';

export const wdStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    background: '#F0F9FF',
  }),
  header: style({
    background: 'linear-gradient(180deg, #0161de 0%, #0072db 100%)',
    padding: '16px',
    color: '#fff',
  }),
  backBtn: style({
    background: 'none',
    border: 'none',
    color: '#fff',
    fontSize: 14,
    padding: '4px 0',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    marginBottom: 8,
  }),
  headerTitle: style({
    fontSize: 17,
    fontWeight: 600,
    textAlign: 'center',
    marginBottom: 4,
  }),
  woMeta: style({
    background: '#fff',
    padding: '12px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  }),
  woTag: style({
    fontSize: 11,
    padding: '2px 8px',
    borderRadius: 4,
    background: '#e8f0fe',
    color: '#0072db',
    fontWeight: 600,
    flexShrink: 0,
  }),
  woNumber: style({
    fontSize: 16,
    fontWeight: 700,
    color: '#0a0a0a',
  }),
  docSection: style({
    flex: 1,
    overflowY: 'auto',
    background: '#f0f2f5',
    padding: '8px',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  }),
  docPage: style({
    background: '#fff',
    borderRadius: 4,
    overflow: 'hidden',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  }),
  docPagePlaceholder: style({
    height: 480,
    background: 'linear-gradient(135deg, #f8fafc 0%, #e5eaf3 100%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    color: '#9ca3af',
    fontSize: 14,
  }),
  docIcon: style({
    width: 64,
    height: 64,
    background: '#e5eaf3',
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 32,
  }),
  footer: style({
    background: '#fff',
    borderTop: '1px solid #e5e7eb',
    padding: '12px 16px',
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexShrink: 0,
  }),
  btnPrimary: style({
    flex: 1,
    height: 44,
    borderRadius: 22,
    background: '#0072db',
    color: '#fff',
    border: 'none',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'pointer',
  }),
  btnSecondary: style({
    flex: 1,
    height: 44,
    borderRadius: 22,
    background: '#fff',
    color: '#0072db',
    border: '1px solid #0072db',
    fontSize: 15,
    fontWeight: 500,
    cursor: 'pointer',
  }),
  btnQuiet: style({
    flex: 1,
    height: 44,
    borderRadius: 22,
    background: '#fff',
    color: '#6a7282',
    border: '1px solid #d1d5db',
    fontSize: 14,
    cursor: 'pointer',
  }),
  signatureArea: style({
    flex: 1,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px 24px 0',
    gap: 12,
  }),
  signaturePrompt: style({
    fontSize: 13,
    color: '#9ca3af',
    textAlign: 'center',
  }),
  signatureCanvas: style({
    width: '100%',
    height: 200,
    border: '1px dashed #d1d5db',
    borderRadius: 8,
    background: '#fafafa',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#d1d5db',
    fontSize: 14,
  }),
  signatureLine: style({
    width: '80%',
    height: 1,
    background: '#d1d5db',
    marginTop: 8,
    alignSelf: 'flex-end',
    marginRight: 20,
  }),
  signedBadge: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '4px 12px',
    borderRadius: 12,
    background: '#f0fdf4',
    color: '#16a34a',
    fontSize: 13,
    fontWeight: 500,
    border: '1px solid #86efac',
  }),
};
