import { style } from '@vanilla-extract/css';

export const woStyles = {
  page: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: '100%',
    backgroundColor: '#f5f7fa',
  }),
  topBar: style({
    backgroundColor: '#0161de',
    padding: '8px 16px',
    flexShrink: 0,
  }),
  topBarTitle: style({
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 700,
    lineHeight: '28px',
  }),
  topBarSub: style({
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    lineHeight: '18px',
  }),
  viewTabsRow: style({
    backgroundColor: '#ffffff',
    padding: '8px 16px',
    borderBottom: '1px solid #f0f0f0',
  }),
  searchRow: style({
    backgroundColor: '#ffffff',
    padding: '10px 16px',
    borderBottom: '1px solid #f0f0f0',
    flexShrink: 0,
  }),
  listSection: style({
    padding: '10px 16px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  }),
  monthGroup: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  }),
  monthTitle: style({
    fontSize: 13,
    color: '#888',
    lineHeight: '18px',
    marginBottom: 4,
  }),
  // Work order card
  card: style({
    backgroundColor: '#ffffff',
    borderRadius: 12,
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
  }),
  cardExpired: style({
    opacity: 0.48,
    backgroundColor: '#f5f7fa',
    borderRadius: 12,
    overflow: 'hidden',
    boxShadow: '0 1px 2px rgba(0,0,0,0.04)',
  }),
  cardBody: style({
    padding: '14px 16px 10px',
  }),
  headerRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  }),
  deviceName: style({
    fontSize: 15,
    fontWeight: 700,
    color: '#222',
    lineHeight: '22px',
    flex: 1,
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  metaRows: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  }),
  metaRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  }),
  metaLabel: style({
    fontSize: 13,
    color: '#999',
    lineHeight: '18px',
    width: 52,
    flexShrink: 0,
  }),
  metaValue: style({
    fontSize: 13,
    color: '#444',
    lineHeight: '18px',
    flex: 1,
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  cardFooter: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    padding: '8px 16px 12px',
    borderTop: '1px solid #f5f5f5',
    gap: 8,
  }),
  cardFooterExpired: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 16px 12px',
    borderTop: '1px solid #f5f5f5',
  }),
  chevronWrap: style({
    display: 'flex',
    alignItems: 'center',
    color: '#bbb',
  }),
  detailActionBtn: style({
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    display: 'flex',
    alignItems: 'center',
  }),
  emptyState: style({
    padding: '40px 0',
    textAlign: 'center',
    color: '#999',
    fontSize: 14,
  }),
  scanRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: '10px 16px',
    borderBottom: '1px solid #f0f0f0',
    flexShrink: 0,
    gap: 8,
  }),
  scanLabel: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#0072db',
    lineHeight: '20px',
  }),
  scanSecondary: style({
    fontSize: 13,
    color: '#aaa',
    lineHeight: '20px',
    marginLeft: 'auto',
    whiteSpace: 'nowrap',
  }),
  loadMoreWrap: style({
    paddingTop: 8,
    paddingBottom: 8,
    display: 'flex',
    justifyContent: 'center',
  }),
  loadMoreBtn: style({
    background: 'none',
    border: '1px solid #d0d0d0',
    borderRadius: 100,
    color: '#0161de',
    fontSize: 13,
    fontWeight: 500,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 8,
    paddingBottom: 8,
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
};
