import { style } from '@vanilla-extract/css';

export const accountSheetStyles = {
  overlay: style({
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 375,
    maxWidth: '100vw',
    backgroundColor: 'rgba(0,0,0,0.45)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    zIndex: 9999,
  }),
  panel: style({
    backgroundColor: '#ffffff',
    borderRadius: '20px 20px 0 0',
    maxHeight: '90%',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    flexShrink: 0,
  }),
  handle: style({
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#d4d4d4',
    margin: '12px auto 0',
    flexShrink: 0,
  }),
  header: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 20px 10px',
    flexShrink: 0,
  }),
  closeBtn: style({
    width: 28,
    height: 28,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    background: '#efefef',
    borderRadius: '50%',
    cursor: 'pointer',
    fontSize: 14,
    color: '#555',
    fontFamily: 'inherit',
  }),
  divider: style({
    height: 1,
    backgroundColor: '#f0f0f0',
  }),

  // ── Rows ──────────────────────────────────────────────────────────────────
  row: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 20px',
    borderTop: '1px solid #f2f4f7',
    width: '100%',
    boxSizing: 'border-box',
  }),
  rowBtn: style({
    background: 'none',
    border: 'none',
    textAlign: 'left',
    fontFamily: 'inherit',
    cursor: 'pointer',
  }),
  rowRight: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  }),
  label: style({
    fontSize: 14,
    color: '#1a2234',
    lineHeight: '20px',
  }),
  value: style({
    fontSize: 14,
    color: '#8898aa',
    lineHeight: '20px',
  }),
  valueBold: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#0161de',
  }),
  valuePrimary: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#1a2234',
    lineHeight: '20px',
  }),
  scopeRowValue: style({
    fontSize: 14,
    color: '#8898aa',
    lineHeight: '20px',
    textAlign: 'right',
    maxWidth: '64%',
  }),

  // ── Campus list ───────────────────────────────────────────────────────────
  campusChipRow: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    padding: '4px 20px 14px 44px',
  }),
  campusChip: style({
    fontSize: 13,
    color: '#4a6fa5',
    lineHeight: '20px',
    selectors: {
      '&::before': {
        content: '"· "',
        color: '#a0b4cc',
      },
    },
  }),
  scopeWrap: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    padding: '12px 20px',
    borderTop: '1px solid #f2f4f7',
  }),
  scopeLabel: style({
    fontSize: 12,
    color: '#8898aa',
  }),
  scopeValue: style({
    fontSize: 14,
    color: '#1a2234',
    lineHeight: '20px',
  }),
  scopeChipRow: style({
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
  }),
  scopeChip: style({
    fontSize: 12,
    color: '#1a2234',
    backgroundColor: '#eef0f4',
    borderRadius: 6,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 4,
    paddingBottom: 4,
    lineHeight: '16px',
  }),

  // ── Upgrade / expansion block ─────────────────────────────────────────────
  blockWrap: style({
    borderTop: '1px dashed #e4e8f0',
    padding: '14px 20px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  }),
  blockTitle: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#1a2234',
  }),
  adjustSummary: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    backgroundColor: '#f8f9fb',
    borderRadius: 8,
    padding: '10px 12px',
  }),
  adjustSummaryLabel: style({
    fontSize: 12,
    color: '#8898aa',
  }),
  adjustSummaryValue: style({
    fontSize: 14,
    color: '#1a2234',
    lineHeight: '20px',
  }),
  statusBadge: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#eff5ff',
    border: '1px solid #b3d4ff',
    borderRadius: 100,
    paddingLeft: 10,
    paddingRight: 12,
    paddingTop: 4,
    paddingBottom: 4,
    alignSelf: 'flex-start',
  }),
  statusDot: style({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: '#0161de',
    flexShrink: 0,
  }),
  statusHint: style({
    fontSize: 12,
    color: '#4a7ad4',
  }),
  metaCard: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    backgroundColor: '#f8f9fb',
    borderRadius: 8,
    padding: '10px 12px',
  }),
  metaRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  }),
  metaLabel: style({
    fontSize: 12,
    color: '#8898aa',
    flexShrink: 0,
    width: 56,
    whiteSpace: 'nowrap',
    lineHeight: '18px',
  }),
  metaValue: style({
    fontSize: 12,
    color: '#444',
    lineHeight: '18px',
  }),
  note: style({
    fontSize: 12,
    color: '#0161de',
    borderLeft: '3px solid #b3d4ff',
    paddingLeft: 8,
  }),
  demoRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 8,
    borderTop: '1px dashed #e0e0e0',
  }),
  demoLabel: style({
    fontSize: 11,
    color: '#aaa',
  }),
  demoBtnApprove: style({
    fontSize: 11,
    color: '#1a7f37',
    backgroundColor: '#e6f9ed',
    border: '1px solid #a8e6bc',
    borderRadius: 100,
    padding: '3px 10px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  demoBtnReject: style({
    fontSize: 11,
    color: '#d0021b',
    backgroundColor: '#fff0f0',
    border: '1px solid #ffb3b3',
    borderRadius: 100,
    padding: '3px 10px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  bottomPad: style({
    height: 20,
  }),
};
