import { style } from '@vanilla-extract/css';

export const bizConsultStyles = {
  overlay: style({
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 375,
    maxWidth: '100vw',
    backgroundColor: 'rgba(0,0,0,0.45)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    zIndex: 9999,
  }),
  panel: style({
    backgroundColor: '#fff',
    borderRadius: '20px 20px 0 0',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '90vh',
  }),
  handle: style({
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#e0e0e0',
    margin: '12px auto 4px',
    flexShrink: 0,
  }),
  header: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    padding: '10px 20px 12px',
    flexShrink: 0,
  }),
  headerTextCol: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
  }),
  title: style({
    fontSize: 16,
    fontWeight: 700,
    color: '#1a1a1a',
    lineHeight: '22px',
  }),
  subtitle: style({
    fontSize: 12,
    color: '#888',
    lineHeight: '16px',
  }),
  closeBtn: style({
    background: 'none',
    border: 'none',
    fontSize: 18,
    color: '#888',
    cursor: 'pointer',
    lineHeight: 1,
    padding: '2px 0 0 8px',
    flexShrink: 0,
    fontFamily: 'inherit',
  }),
  body: style({
    overflowY: 'auto',
    padding: '4px 20px 8px',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    flex: 1,
  }),
  fieldRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
  }),
  fieldGroup: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  }),
  label: style({
    fontSize: 13,
    fontWeight: 500,
    color: '#444',
    lineHeight: '18px',
  }),
  required: style({
    color: '#e53e3e',
  }),
  optional: style({
    color: '#aaa',
    fontWeight: 400,
  }),
  input: style({
    width: '100%',
    fontSize: 14,
    borderRadius: 8,
    border: '1.5px solid #d0d5dd',
    outline: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    padding: '9px 12px',
    color: '#222',
  }),
  phoneLocked: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '9px 12px',
    borderRadius: 8,
    border: '1.5px solid #ebebeb',
    backgroundColor: '#f9f9f9',
    gap: 10,
  }),
  phoneLockedValue: style({
    fontSize: 14,
    color: '#aaa',
    fontWeight: 500,
    flex: 1,
    letterSpacing: '0.04em',
  }),
  phoneLockedNote: style({
    fontSize: 11,
    color: '#ccc',
  }),
  timeChips: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  }),
  timeChip: style({
    fontSize: 13,
    fontWeight: 500,
    color: '#555',
    backgroundColor: '#f5f5f5',
    border: '1.5px solid #e8e8e8',
    borderRadius: 100,
    padding: '5px 14px',
    cursor: 'pointer',
    fontFamily: 'inherit',
    lineHeight: '18px',
  }),
  timeChipActive: style({
    backgroundColor: '#e8f0fe',
    borderColor: '#a8c4f5',
    color: '#1558b0',
  }),
  textarea: style({
    width: '100%',
    fontSize: 14,
    borderRadius: 8,
    border: '1.5px solid #d0d5dd',
    outline: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    padding: '9px 12px',
    resize: 'none',
    color: '#222',
    lineHeight: '20px',
  }),
  footer: style({
    flexShrink: 0,
    padding: '14px 20px 28px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  }),
  submitBtn: style({
    width: '100%',
    backgroundColor: '#0161de',
    color: '#fff',
    border: 'none',
    borderRadius: 10,
    fontSize: 15,
    fontWeight: 600,
    padding: '13px 0',
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  submitBtnDisabled: style({
    backgroundColor: '#c0cfe8',
    cursor: 'not-allowed',
  }),
  dividerRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  }),
  dividerLine: style({
    flex: 1,
    height: 1,
    backgroundColor: '#ebebeb',
  }),
  dividerText: style({
    fontSize: 12,
    color: '#ccc',
  }),
  callRow: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 3,
  }),
  callNote: style({
    fontSize: 12,
    color: '#aaa',
  }),
  callLink: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#0161de',
    textDecoration: 'none',
  }),
  successState: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '28px 24px 36px',
    gap: 8,
  }),
  successIcon: style({
    width: 52,
    height: 52,
    borderRadius: '50%',
    backgroundColor: '#e8f7ef',
    color: '#0a7c3e',
    fontSize: 24,
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  }),
  successTitle: style({
    fontSize: 17,
    fontWeight: 700,
    color: '#1a1a1a',
  }),
  successDesc: style({
    fontSize: 13,
    color: '#777',
    textAlign: 'center',
    lineHeight: '20px',
    maxWidth: 260,
  }),
  closePrimary: style({
    marginTop: 12,
    width: '100%',
    backgroundColor: '#f5f5f5',
    color: '#444',
    border: 'none',
    borderRadius: 10,
    fontSize: 15,
    fontWeight: 500,
    padding: '12px 0',
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
};
