import { style } from '@vanilla-extract/css';

export const campusSheetStyles = {
  overlay: style({
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 375,
    maxWidth: '100vw',
    backgroundColor: 'rgba(0,0,0,0.45)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    zIndex: 9999,
  }),
  panel: style({
    backgroundColor: '#ffffff',
    borderRadius: '20px 20px 0 0',
    maxHeight: '88%',
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    flexShrink: 0,
    overflow: 'hidden',
  }),
  handle: style({
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#d4d4d4',
    margin: '12px auto 0',
    flexShrink: 0,
  }),
  header: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 20px 10px',
    flexShrink: 0,
  }),
  closeBtn: style({
    width: 28,
    height: 28,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    background: '#efefef',
    borderRadius: '50%',
    cursor: 'pointer',
    fontSize: 14,
    color: '#555',
    fontFamily: 'inherit',
  }),
  divider: style({
    height: 1,
    backgroundColor: '#f0f0f0',
    flexShrink: 0,
  }),

  // ── Scrollable body ───────────────────────────────────────────────────────
  scrollBody: style({
    flex: 1,
    overflowY: 'auto',
    minHeight: 0,
  }),
  sectionLabel: style({
    fontSize: 12,
    fontWeight: 600,
    color: '#8898aa',
    letterSpacing: '0.4px',
    padding: '16px 20px 8px',
  }),

  // ── Campus list rows ──────────────────────────────────────────────────────
  campusList: style({
    display: 'flex',
    flexDirection: 'column',
  }),
  campusRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: '14px 20px',
    background: 'none',
    border: 'none',
    borderBottom: '1px solid #f2f4f7',
    cursor: 'pointer',
    textAlign: 'left',
    fontFamily: 'inherit',
    width: '100%',
    boxSizing: 'border-box',
    minHeight: 52,
  }),
  campusRowSelected: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: '14px 20px',
    backgroundColor: '#f0f6ff',
    border: 'none',
    borderBottom: '1px solid #d9eaff',
    cursor: 'pointer',
    textAlign: 'left',
    fontFamily: 'inherit',
    width: '100%',
    boxSizing: 'border-box',
    minHeight: 52,
  }),
  checkCircle: style({
    width: 22,
    height: 22,
    borderRadius: '50%',
    border: '2px solid #c8d4e4',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  checkCircleFilled: style({
    width: 22,
    height: 22,
    borderRadius: '50%',
    backgroundColor: '#0161de',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  campusName: style({
    fontSize: 14,
    color: '#1a2234',
    lineHeight: '20px',
    flex: 1,
    textAlign: 'left',
  }),
  campusNameSelected: style({
    fontSize: 14,
    color: '#0161de',
    fontWeight: 500,
    lineHeight: '20px',
    flex: 1,
    textAlign: 'left',
  }),

  // ── Sales contact (optional) ──────────────────────────────────────────────
  salesSection: style({
    padding: '20px 20px 8px',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    borderTop: '1px solid #f2f4f7',
    marginTop: 4,
  }),
  salesLabel: style({
    fontSize: 13,
    fontWeight: 600,
    color: '#444',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  }),
  optionalTag: style({
    fontSize: 11,
    color: '#888',
    backgroundColor: '#f0f0f0',
    borderRadius: 4,
    padding: '1px 6px',
    fontWeight: 400,
  }),
  salesHint: style({
    fontSize: 12,
    color: '#888',
  }),
  textInput: style({
    border: '1.5px solid #e0e0e0',
    borderRadius: 10,
    padding: '10px 12px',
    fontSize: 14,
    color: '#222',
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    outline: 'none',
    selectors: {
      '&:focus': {
        borderColor: '#0161de',
      },
    },
  }),

  // ── Footer note ───────────────────────────────────────────────────────────
  footerNote: style({
    fontSize: 12,
    color: '#8898aa',
    padding: '16px 20px 24px',
    lineHeight: '18px',
  }),

  // ── Submit bar (sticky) ───────────────────────────────────────────────────
  submitBar: style({
    padding: '12px 20px 28px',
    borderTop: '1px solid #f0f0f0',
    backgroundColor: '#ffffff',
    flexShrink: 0,
  }),
  submitBtn: style({
    width: '100%',
    backgroundColor: '#0161de',
    color: '#ffffff',
    border: 'none',
    borderRadius: 12,
    padding: '14px 20px',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  }),
  submitBtnDisabled: style({
    width: '100%',
    backgroundColor: '#c4d0e0',
    color: '#ffffff',
    border: 'none',
    borderRadius: 12,
    padding: '14px 20px',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'not-allowed',
    fontFamily: 'inherit',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  }),
  submitCount: style({
    fontSize: 13,
    fontWeight: 400,
    opacity: 0.85,
  }),
};
