import { style } from '@vanilla-extract/css';

export const caseHeaderStyles = {
  header: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    width: '100%',
    flexShrink: 0,
    padding: '8px 12px 10px 16px',
    borderBottom: '1px solid #ececec',
    background: '#ffffff',
  }),
  row: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    width: '100%',
    padding: 0,
    border: 'none',
    background: 'none',
    textAlign: 'left',
    cursor: 'pointer',
  }),
  caseRow: style({
    paddingLeft: 48,
    gap: 8,
  }),
  glyph: style({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    flexShrink: 0,
    borderRadius: 8,
    background: '#f0f9ff',
  }),
  device: style({
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    fontWeight: 600,
    color: '#1f2937',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  chip: style({
    flexShrink: 0,
    padding: '1px 6px',
    borderRadius: 4,
    fontSize: 11,
    lineHeight: '16px',
    background: '#f0f9ff',
    color: '#006ebd',
  }),
  chipClosed: style({
    background: '#eef0f3',
    color: '#5b6270',
  }),
  meta: style({
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    lineHeight: '18px',
    color: '#6a7282',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  chevron: style({
    width: 16,
    height: 16,
    flexShrink: 0,
    color: '#9aa1ac',
  }),
};
