import { style } from '@vanilla-extract/css';

export const sortControlStyles = {
  wrap: style({
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 12,
    flexShrink: 0,
  }),
  dirBtn: style({
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    background: 'none',
    border: 'none',
    color: '#8a94a6',
    fontSize: 12,
    fontWeight: 500,
    height: 20,
    lineHeight: '20px',
    fontFamily: 'inherit',
    cursor: 'pointer',
    padding: 0,
  }),
  labelBtn: style({
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    background: 'none',
    border: 'none',
    color: '#0161de',
    fontSize: 12,
    fontWeight: 500,
    height: 20,
    lineHeight: '20px',
    fontFamily: 'inherit',
    cursor: 'pointer',
    padding: 0,
  }),
  backdrop: style({
    position: 'fixed',
    inset: 0,
    zIndex: 40,
  }),
  dropdown: style({
    position: 'absolute',
    top: 'calc(100% + 4px)',
    right: 0,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    overflow: 'hidden',
    zIndex: 50,
    minWidth: 110,
    boxShadow: '0 4px 16px rgba(0,0,0,0.12)',
  }),
  dropdownItem: style({
    display: 'block',
    width: '100%',
    padding: '10px 14px',
    background: 'none',
    border: 'none',
    fontSize: 13,
    color: '#333',
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
  }),
  dropdownItemActive: style({
    backgroundColor: '#e8f2ff',
    color: '#0161de',
    fontWeight: 600,
  }),
};
