import { style } from '@vanilla-extract/css';

export const deviceCardStyles = {
  card: style({
    width: '100%',
    cursor: 'pointer',
    overflow: 'hidden',
  }),
  inner: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'stretch',
    minHeight: 80,
  }),
  iconBlock: style({
    width: 72,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    gap: 6,
  }),
  iconBlockMr: style({ backgroundColor: '#F0F8FA' }),
  iconBlockCt: style({ backgroundColor: '#F0F8FA' }),
  iconBlockIgt: style({ backgroundColor: '#F0F8FA' }),
  iconBlockUs: style({ backgroundColor: '#F0F8FA' }),
  iconBlockOther: style({ backgroundColor: '#F0F8FA' }),
  iconBlockLabel: style({
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: '0.02em',
    lineHeight: '14px',
    textAlign: 'center',
    color: '#0072DB',
  }),
  iconBlockLabelMr: style({}),
  iconBlockLabelCt: style({}),
  iconBlockLabelIgt: style({}),
  iconBlockLabelUs: style({}),
  iconBlockLabelOther: style({}),
  content: style({
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '12px 10px 12px 14px',
    gap: 2,
  }),
  deviceName: style({
    color: '#00126e',
    fontWeight: 700,
    lineHeight: '20px',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  metaRow: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    alignItems: 'flex-start',
    marginTop: 2,
    minWidth: 0,
  }),
  metaText: style({
    fontSize: 12,
    lineHeight: '16px',
    minWidth: 0,
    whiteSpace: 'normal',
    wordBreak: 'break-word',
  }),
  dot: style({
    width: 3,
    height: 3,
    borderRadius: '50%',
    backgroundColor: 'rgba(0,0,0,0.25)',
    flexShrink: 0,
  }),
  tagsRow: style({
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 6,
  }),
  tagChip: style({
    display: 'inline-flex',
    alignItems: 'center',
    padding: '2px 8px',
    borderRadius: 4,
    fontSize: 12,
    fontWeight: 500,
    whiteSpace: 'nowrap',
    lineHeight: '18px',
  }),
  tagChipError: style({ backgroundColor: '#fff5f6', color: '#d60012' }),
  tagChipWarn: style({ backgroundColor: '#fff5f0', color: '#c24100' }),
  tagChipCaution: style({ backgroundColor: '#fff7d1', color: '#806a00' }),
  tagChipInfo: style({ backgroundColor: '#f0f9ff', color: '#0072DB' }),
  tagChipNeutral: style({ backgroundColor: '#f3f4f6', color: '#6b7280' }),
  chevron: style({
    flexShrink: 0,
    alignSelf: 'center',
    color: 'rgba(0,0,0,0.25)',
    marginRight: 10,
  }),
  customNameNote: style({
    fontSize: 12,
    color: 'rgba(0,0,0,0.4)',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
};
