import { style } from '@vanilla-extract/css';

export const deviceSummaryStyles = {
  card: style({
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    padding: 0,
    borderRadius: 12,
    border: '1px solid #dce3ec',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(16, 42, 77, 0.06)',
    cursor: 'pointer',
    textAlign: 'left',
  }),
  head: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: '12px 14px',
    borderBottom: '1px solid #eef1f5',
  }),
  glyph: style({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 38,
    height: 38,
    flexShrink: 0,
    borderRadius: 10,
    backgroundColor: '#f0f8fa',
  }),
  headText: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    minWidth: 0,
    flex: 1,
  }),
  name: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#1f2937',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  place: style({
    fontSize: 12,
    color: '#6a7282',
  }),
  chipRow: style({
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 4,
  }),
  chip: style({
    display: 'inline-flex',
    alignItems: 'center',
    padding: '1px 6px',
    borderRadius: 4,
    fontSize: 11,
    lineHeight: '16px',
    whiteSpace: 'nowrap',
  }),
  chipError: style({ backgroundColor: '#fff5f6', color: '#d60012' }),
  chipWarn: style({ backgroundColor: '#fff5f0', color: '#c24100' }),
  chipCaution: style({ backgroundColor: '#fff7d1', color: '#806a00' }),
  chipInfo: style({ backgroundColor: '#f0f9ff', color: '#0072db' }),
  rows: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: '12px 14px',
  }),
  row: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  }),
  key: style({
    width: 60,
    flexShrink: 0,
    fontSize: 12,
    color: '#9aa1ac',
  }),
  value: style({
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    color: '#3a4250',
  }),
  footer: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    padding: '9px 14px',
    borderTop: '1px solid #eef1f5',
    fontSize: 12,
    color: '#0072db',
  }),
  chevron: style({
    width: 14,
    height: 14,
    flexShrink: 0,
  }),
};
