import { style } from '@vanilla-extract/css';

export const composerStyles = {
  composer: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: '8px 12px 12px',
    borderTop: '1px solid #ececec',
    backgroundColor: '#ffffff',
  }),
  previewRow: style({
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    overflowX: 'auto',
  }),
  contextRow: style({
    display: 'flex',
    flexDirection: 'row',
  }),
  contextChip: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    maxWidth: '100%',
    padding: '4px 8px 4px 10px',
    borderRadius: 14,
    backgroundColor: '#eef4fb',
    fontSize: 12,
    color: '#0072db',
  }),
  contextRemove: style({
    border: 'none',
    background: 'none',
    padding: 0,
    fontSize: 15,
    lineHeight: 1,
    color: '#6a7282',
    cursor: 'pointer',
  }),
  previewItem: style({
    position: 'relative',
    width: 56,
    height: 56,
    flexShrink: 0,
  }),
  previewImage: style({
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    borderRadius: 6,
    display: 'block',
  }),
  previewRemove: style({
    position: 'absolute',
    top: -6,
    right: -6,
    width: 18,
    height: 18,
    borderRadius: '50%',
    border: 'none',
    backgroundColor: '#00000099',
    color: '#ffffff',
    fontSize: 13,
    lineHeight: 1,
    cursor: 'pointer',
    padding: 0,
  }),
  inputRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  }),
  actionPanel: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    maxHeight: 360,
    overflowY: 'auto',
  }),
  actionBar: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  }),
  actionChip: style({
    border: '1px solid #dce3ec',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    padding: '4px 12px',
    fontSize: 12,
    lineHeight: '18px',
    color: '#3b4653',
    cursor: 'pointer',
  }),
  actionChipActive: style({
    borderColor: '#0072db',
    backgroundColor: '#eef4fb',
    color: '#0072db',
  }),
  fieldWrapper: style({
    flex: 1,
    minWidth: 0,
  }),
  hiddenInput: style({
    display: 'none',
  }),
};
