import { style } from '@vanilla-extract/css';

export const quickEntryStyles = {
  card: style({
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    width: '100%',
    alignSelf: 'flex-start',
    padding: '12px 14px',
    borderRadius: 12,
    border: '1px solid #dce3ec',
    backgroundColor: '#ffffff',
    boxShadow: '0 1px 4px rgba(16, 42, 77, 0.06)',
  }),
  cardWithClose: style({
    paddingTop: 30,
  }),
  close: style({
    position: 'absolute',
    top: 6,
    right: 6,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    border: 'none',
    background: 'none',
    padding: 0,
    cursor: 'pointer',
    color: '#9aa1ac',
  }),
  closeIcon: style({
    width: 16,
    height: 16,
  }),
  hint: style({
    fontSize: 12,
    color: '#9aa1ac',
  }),
  back: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    alignSelf: 'flex-start',
    border: 'none',
    background: 'none',
    padding: 0,
    cursor: 'pointer',
    fontSize: 12,
    color: '#6a7282',
  }),
  backIcon: style({
    width: 14,
    height: 14,
  }),
  list: style({
    display: 'flex',
    flexDirection: 'column',
  }),
  scrollList: style({
    display: 'flex',
    flexDirection: 'column',
    maxHeight: 268,
    overflowY: 'auto',
  }),
  optionRow: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    border: 'none',
    borderTop: '1px solid #eef1f5',
    background: 'none',
    padding: '11px 0',
    cursor: 'pointer',
    textAlign: 'left',
    selectors: {
      '&:first-child': { borderTop: 'none' },
    },
  }),
  optionText: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    flex: 1,
    minWidth: 0,
  }),
  optionTitle: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#1f2937',
  }),
  optionDesc: style({
    fontSize: 12,
    color: '#9aa1ac',
  }),
  glyph: style({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 34,
    height: 34,
    flexShrink: 0,
    borderRadius: 9,
    backgroundColor: '#f0f8fa',
  }),
  chevron: style({
    width: 15,
    height: 15,
    flexShrink: 0,
    color: '#a6acb5',
  }),
  chips: style({
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  }),
  chip: style({
    border: '1px solid #cfe0f5',
    borderRadius: 999,
    background: 'none',
    padding: '7px 14px',
    cursor: 'pointer',
    fontSize: 13,
    color: '#0072db',
  }),
};
