import { style } from '@vanilla-extract/css';

export const subSheetStyles = {
  overlay: style({
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 375,
    maxWidth: '100vw',
    backgroundColor: 'rgba(0,0,0,0.45)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    zIndex: 9999,
  }),
  panel: style({
    backgroundColor: '#ffffff',
    borderRadius: '20px 20px 0 0',
    maxHeight: '85%',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    flexShrink: 0,
  }),
  handle: style({
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#d4d4d4',
    margin: '12px auto 0',
    flexShrink: 0,
  }),
  header: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 20px 6px',
    flexShrink: 0,
  }),
  title: style({
    fontSize: 17,
    fontWeight: 600,
    color: '#111827',
  }),
  closeBtn: style({
    width: 28,
    height: 28,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    background: '#efefef',
    borderRadius: '50%',
    cursor: 'pointer',
    fontSize: 14,
    color: '#555',
    fontFamily: 'inherit',
  }),
  desc: style({
    fontSize: 13,
    color: '#6b7280',
    padding: '0 20px 12px',
  }),
  divider: style({
    height: 1,
    backgroundColor: '#f0f0f0',
  }),
  list: style({
    display: 'flex',
    flexDirection: 'column',
    padding: '4px 20px',
  }),
  row: style({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 0',
    borderBottom: '1px solid #f3f4f6',
  }),
  rowLeft: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    flex: 1,
    marginRight: 16,
  }),
  rowLabel: style({
    fontSize: 15,
    fontWeight: 500,
    color: '#111827',
  }),
  rowDesc: style({
    fontSize: 12,
    color: '#9ca3af',
  }),
  switchOff: style({
    width: 46,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#e5e7eb',
    border: 'none',
    cursor: 'pointer',
    position: 'relative',
    flexShrink: 0,
    selectors: {
      '&::after': {
        content: '""',
        display: 'block',
        position: 'absolute',
        width: 22,
        height: 22,
        borderRadius: '50%',
        backgroundColor: '#ffffff',
        top: 2,
        left: 2,
        boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
      },
    },
  }),
  switchOn: style({
    width: 46,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#0161de',
    border: 'none',
    cursor: 'pointer',
    position: 'relative',
    flexShrink: 0,
    selectors: {
      '&::after': {
        content: '""',
        display: 'block',
        position: 'absolute',
        width: 22,
        height: 22,
        borderRadius: '50%',
        backgroundColor: '#ffffff',
        top: 2,
        left: 20,
        boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
      },
    },
  }),
  footer: style({
    padding: '16px 20px 32px',
  }),
};
