import { style } from '@vanilla-extract/css';

export const toastStyles = {
  wrap: style({
    position: 'fixed',
    left: 0,
    right: 0,
    bottom: 92,
    display: 'flex',
    justifyContent: 'center',
    pointerEvents: 'none',
    zIndex: 2000,
    padding: '0 24px',
  }),
  toast: style({
    pointerEvents: 'auto',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    maxWidth: 360,
    width: 'fit-content',
    paddingTop: 11,
    paddingBottom: 11,
    paddingLeft: 16,
    paddingRight: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(28,36,51,0.94)',
    boxShadow: '0 8px 24px rgba(15,26,45,0.28)',
  }),
  message: style({
    fontSize: 13,
    lineHeight: '18px',
    color: '#ffffff',
    flex: 1,
  }),
  actionBtn: style({
    flexShrink: 0,
    background: 'none',
    border: 'none',
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 600,
    color: '#6cb6ff',
    cursor: 'pointer',
    paddingLeft: 6,
    paddingRight: 6,
  }),
};
