import { style } from '@vanilla-extract/css';

export const transferCardStyles = {
  wrap: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
    padding: '14px 0 6px',
  }),
  caption: style({
    fontSize: 12,
    color: '#9aa1ac',
  }),
  card: style({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    padding: '12px 14px',
    border: '1px solid #cfe0f5',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    boxShadow: '0 1px 4px rgba(16, 42, 77, 0.08)',
    cursor: 'pointer',
    textAlign: 'left',
  }),
  icon: style({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#f0f8fa',
    flexShrink: 0,
  }),
  body: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    flex: 1,
    minWidth: 0,
  }),
  title: style({
    fontSize: 14,
    fontWeight: 600,
    color: '#1f2937',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  meta: style({
    fontSize: 12,
    color: '#6a7282',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  action: style({
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    flexShrink: 0,
    fontSize: 13,
    fontWeight: 600,
    color: '#0072db',
  }),
  chevron: style({
    width: 15,
    height: 15,
  }),
};
