import type { AppMessage } from '../types/message';

// Today: April 29, 2026
// Generated from device data: contract + PM fields
export const messageData: AppMessage[] = [
  // === Admin-only: Contract alerts ===
  {
    id: 'msg-001',
    category: 'contract-expired',
    title: 'MR 5300 已脱保',
    body: '该设备服务合同已于 2025-12-31 到期，当前无服务保障，建议尽快续约或申请临时维护支持。',
    time: '2026-01-01',
    isRead: false,
    deviceId: 'dev-004',
    deviceName: 'MR 5300',
    forAdminOnly: true,
  },
  {
    id: 'msg-002',
    category: 'contract-expiry',
    title: 'Affiniti 70 合同即将到期',
    body: '该设备服务合同将于 2026-06-20 到期，距今仅 52 天，请提前联系服务代表进行续约。',
    time: '2026-04-28',
    isRead: false,
    deviceId: 'dev-006',
    deviceName: 'Affiniti 70',
    forAdminOnly: true,
  },
  {
    id: 'msg-003',
    category: 'contract-expiry',
    title: 'Azurion M3 合同即将到期',
    body: '该设备服务合同将于 2026-07-15 到期，距今 77 天，请关注续约进度。',
    time: '2026-04-27',
    isRead: false,
    deviceId: 'dev-002',
    deviceName: 'Azurion M3',
    forAdminOnly: true,
  },
  {
    id: 'msg-004',
    category: 'contract-expiry',
    title: 'BigBore CT 7500 合同提醒',
    body: '该设备服务合同将于 2026-09-30 到期，距今 154 天，建议本季度内完成续约审批。',
    time: '2026-04-20',
    isRead: true,
    deviceId: 'dev-005',
    deviceName: 'BigBore CT 7500',
    forAdminOnly: true,
  },
  // === Admin-only: PM risk ===
  {
    id: 'msg-005',
    category: 'pm-risk',
    title: 'Lumify 便携超声 存在PM风险',
    body: '该设备无服务合同，长期未执行预防性维护，建议安排自费保养或签订合同。',
    time: '2026-04-25',
    isRead: false,
    deviceId: 'dev-007',
    deviceName: 'Lumify 便携超声',
    forAdminOnly: true,
  },
  {
    id: 'msg-006',
    category: 'pm-risk',
    title: 'MR 5300 PM风险升高',
    body: '该设备已脱保，上次保养日期为 2025-06-10，已超过 10 个月未进行预防性维护，建议优先处理。',
    time: '2026-04-22',
    isRead: true,
    deviceId: 'dev-004',
    deviceName: 'MR 5300',
    forAdminOnly: true,
  },
  // === Shared: PM plan reminders (both roles) ===
  {
    id: 'msg-007',
    category: 'pm-plan',
    title: '本月保养计划：5台设备',
    body: '以下设备本月有PM计划：Azurion M3（5-1）、BigBore CT 7500（5-1）、Vereos PET/CT（5-1）、Ingenia 3.0T（5-15）、Affiniti 70（5-15），请知悉并安排停机时间。',
    time: '2026-04-29',
    isRead: false,
    forAdminOnly: false,
  },
  // === Shared: Work order updates ===
  {
    id: 'msg-008',
    category: 'order-update',
    title: '工单 WO128923783 已派工',
    body: 'Ingenia 3.0T 维修工单已由工程师张伟接单，预计 2026-04-30 上门处理。',
    time: '2026-04-29',
    isRead: false,
    forAdminOnly: false,
  },
  {
    id: 'msg-009',
    category: 'order-update',
    title: '工单 WO128923784 等待签字',
    body: 'Ingenia 3.0T 保养工单已完成，请前往工单列表完成签字确认。',
    time: '2026-04-28',
    isRead: false,
    forAdminOnly: false,
  },
  {
    id: 'msg-010',
    category: 'order-update',
    title: '工单 WO128923700 已关闭',
    body: 'Azurion M3 维修工单已于 2025-10-22 完成并关闭，感谢您的配合。',
    time: '2025-10-22',
    isRead: true,
    forAdminOnly: false,
  },
];
